### ISSUE TITLE
Markdown content handling

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#12]
The vast majority of _relatively_ static content will be kept in a separate github repository than this one as Markdown with frontmatter. The reasons for this are to separate the code of the site from it's content, separate access for contributors, etc. 

We need the following features: 

- [x] Typical SEO/HTML HEAD metadata taken from frontmatter
- [x] Simple tagging via frontmatter
- [x] `content/index.md` becomes `/` and `/index.html` and `content/about/leadership.md` becomes `/about/leadership/` etc 
- [x] Ability to create Hugo like shortcodes in Markdown so choice of extensible Python Markdown library is a key decision
- [ ] Ability to reference and link files from `content` easily.  i.e. it be possible to insert an image with Markdown that is relative to the Mardown file itself i.e. `content/about/group-photo.jpg` 
- [x] App should assume this second git repo is mounted in the same container/filesystem and be periodically updated. Ideally will get updated via webhook from Github on merge to `main` branch 
- [ ] Django view that renders this should cache the results for `settings.MARKDOWN_CONTENT_CACHE_SECONDS` seconds 
- [ ] Detailed content writing documentation in Markdown in `docs/` folder of content repo (and linked from README)
- [x] Needs to support code blocks and syntax highlighting

Keep in mind that this will be used for content such as: 

- blog posts
- general evergreen content pages ("How to Contribute", "Our Review Process", etc) 
- wiki content (which is one of the main drivers for a shortcode like system) 

For ease of development it's perfectly fine to start with a `content` directory here in this repo but it will get moved to a separate repo in the near future.

**Comment by vinniefalco** [comment]
We are using Asciidoc for this now. Update the issue or if there is a newer one that replaces this, close this issue.
