### ISSUE TITLE
Option for users to receive an email for forum thread replies quickly

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#13]
They have some old guard that don't want to lose the mailing list and are going to try to recreate the experience as much as possible.  Email service in question TBD. 

Machina has a delay built in which needs to go away see this PR from their old repo:

https://github.com/CPPAlliance/bweb/pull/3

And this issue: 

https://github.com/ellmetha/django-machina/issues/198

**Comment by gregnewman** [comment]
We are no longer using the forum so closing this issue
