### ISSUE TITLE
Setting up regular refresh of library/author/maintainer/issue/PR data via GitHub 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#178]
## Description
The data in dev for current version libraries is all there now, and the bug with sublibraries has been fixed. However, we still need to set up a regular refresh schedule to keep the data in sync. Currently, the refresh takes several minutes to run due to all the API calls, and we may want to break it up into celery tasks. Additionally, we need to set the Github API secret in dev, as I set it manually in the CLI but it should be a formal kube secret. 

## Tasks
- Set up a regular refresh schedule for dev, possibly hourly
- Break up refresh into celery tasks to speed up process
- Set the Github API secret in dev as a kube secret under the cpalliance account

## Additional Information
- Without downloading PRs and Issues, the refresh takes several minutes to run due to all the API calls. With the PRs and issues, it takes upwards of 15 minutes. 
- Probably the way that makes the most sense is to call the celery tasks when looping over libraries, and let the celery tasks make the API calls.

**Comment by nessita** [comment]
Assigning this to @frankwiles since I believe the pending item is to setup secrets for the celery task to be able to fetch GH information.

**Comment by williln** [comment]
Token issue addressed in https://github.com/cppalliance/temp-site/pull/528
