### ISSUE TITLE
Add replacement path for different sites

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#198]
- [ ] Make `core.boostrenderer.get_s3_keys()` determine which JSON configuration by an environment variable
- [ ] Add `DOC_ENV` setting which will be at first either `develop` or `master`
- [ ] Adjust rendering so that it will do f-string replacement of `<ENV>` in the s3_paths with the value in `settings.DOC_ENV`

**Comment by frankwiles** [comment]
This plan was abandoned or reworked into a new plan and is completed.

**Comment by sdarwin** [comment]
Hi @frankwiles  "This plan is completed."   Actually, there is still some sort of open issue about `s3_paths` in terms of `develop` or `master`. `stage_static_config.json` only points to `develop`.  And, what about the `master` branch? There is no `production_static_config.json` file.   See https://github.com/cppalliance/temp-site/issues/725

**Comment by frankwiles** [comment]
Sorry should have phrased it that this is a old/duplicate of #725
