### ISSUE TITLE
Mailman3 Integration

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#204]
# Overall Plan 

Integrating Mailman3's django based archive view and general user management web UI seems like the easiest path and 
the one with the least future maintenance headaches. 

Mailman3 does a lot of local filesystem file manipulation, so it will be best to use it's own interfaces to injecting a message from our "forum" changes to the web UI.  This will involve: 

- [ ] Small Python based API running on same host/pod as mailman3 itself
- [ ] Django site will POST to this API when sending a message to a list with the user info and message contents
- [ ] API will use similar code to [mailman3 CLI inject message](https://gitlab.com/mailman/mailman/-/blob/master/src/mailman/commands/cli_inject.py) specifically the `inject_text()` function

## Assumptions 

1. Mailing list users will have to register and have an account in Boost.org website to join mailing list and manage subscription options
2. We will use same "claim your account" flows we were planning to use for Authors/Maintainers 

## Questions

1. Should mailing list registration question be part of website signup flow? 
2. Any special processing of messages coming from the forum web UI?

**Comment by frankwiles** [comment]
@nessita I merged in the branch with the docker changes and looked into the `auth_user` migration issue.  I believe what we need to do at this point is: 

1. **NOT** include mailman-web as a Docker container in compose
2. Add [hyperkitty](https://pypi.org/project/HyperKitty/) as a pip dependency in our `requirements.in`
3. Configure it to live happily in our Django project

Since it will be using OUR Django settings, this will sync the custom user model.  FYI I checked and hyperkitty is properly FK'ing using `settings.AUTH_USER_MODEL` and hasn't stupidly hard coded `django.contrib.auth.models.User` or anything weird.  

Let me know if you run into issues!

**Comment by sdarwin** [comment]
Testing mailman3 previously, such as https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/ , it appeared clicking "Reply" opened the user's mail client.  So they could send an email to the list.     That user experience would be worse than any forum software, where you may easily reply within the web UI.

It's great to discover that....  If you are logged into mailman3, and then as a signed-in user click "Reply", you get a text box in the webpage.  Not a redirect to an external mail client.  

So, there is no issue there, it is similar to a forum discussion board.

**Comment by sdarwin** [comment]
Mailman3 is composed of 3 main parts:
- postorius
- hyperkitty
- mailman-core

 Include postorius and hyperkitty into the web project, via _both_ these pip packages:  
  - mailman-web
  - mailman-hyperkitty 

The third pip package is installed on the mailman-core server only.   External to the web project. 
- mailman

In terms of the database, a similar idea.  The mailman-web database would become part of the main Django database.    The mailman database is separate. Exclude mailman-core from both the web project and the web database, and even from docker-compose.  

We can install mailman-core on dedicated servers.  Postorius will reach it at MAILMAN_REST_API_URL in settings.py.

General discussion: https://github.com/cppalliance/ansible-mailman3/tree/cppal-core/docs

Settings.py to merge: https://github.com/cppalliance/ansible-mailman3/blob/cppal-core/docs/settings.py.example1

Reference of how to install standard mailman3 on a standalone server: https://github.com/cppalliance/ansible-mailman3/blob/cppal-full

A functional test instance of mailman, but not integrated with the website: https://mailman-staging.boost.cpp.al.  That URL might change soon.

**Comment by sdarwin** [comment]
In terms of docker-compose:  
- mailman-core - yes this could be another docker container.  But it should have its own database in postgres.  Do not connect to the same web database.
- mailman-web - would **not** be another separate docker container. If it's being merged to the main website it would be included in the existing django codebase.

**Comment by frankwiles** [comment]
This plan was abandoned in favor of a standalone Mailman Django project and have it use boost.org for auth via OAuth2
