### ISSUE TITLE
Initial instructions for non-experts

### ISSUE THREAD

**Issue by alandefreitas** [cppalliance/temp-site#211]
I am currently following the initial instructions in README.md, and I wanted to share some feedback that might be helpful for other beginners like myself if we could update this document.

> Copy .env-dist to .env and adjust values to match your local environment:

`.env-template`?

> developer utility commands, are codified in our `justfile`

Then it goes on to the commands without `just`. It would be good to make clear if I need `just` or not. If so, some instructions to install it. If not, just mention it when it's needed. 

I spent a few minutes googling about it and haven't used it yet.

> docker-compose up

I don't have much experience with `docker` but I think that will require `sudo` from most people who got it from `apt-get`. `sudo` is not really part of the command but an admonition or something would be good.

> This project will use Python 3.9

`sudo docker-compose up` failed for me precisely at

```
Setting up python3.7-minimal (3.7.3-2+deb10u4) ...
Traceback (most recent call last):
  File "/usr/lib/python3.7/py_compile.py", line 212, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/py_compile.py", line 204, in main
    compile(filename, doraise=True)
  File "/usr/lib/python3.7/py_compile.py", line 169, in compile
    importlib._bootstrap_external._write_atomic(cfile, bytecode, mode)
  File "<frozen importlib._bootstrap_external>", line 112, in _write_atomic
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.7/__pycache__/__future__.cpython-37.pyc.139766204777840'
dpkg: error processing package python3.7-minimal (--configure):
Errors were encountered while processing:
 python3.7-minimal
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt update && apt install -y build-essential gcc python-dev postgresql-client && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
ERROR: Service 'web' failed to build : Build failed
```

Maybe the script to supposed to update python to 3.9 after that. But I don't know. I couldn't get passed that yet. 

As I'm trying to fix the issue, I noticed that there are multiple scripts calling each other, and all of them are located in the root directory. While this might be a common practice, it is not something I am used to seeing in the projects I have worked on previously. I was wondering if it would be possible to tidy things up a bit and only keep the scripts that are required for the functionality of the tools in the root directory. This would make it easier for me to navigate and understand the project structure.

I'll probably be back when I get passed line 25 of README.md. :)

**Comment by gregnewman** [comment]
This looks like it was resolved. I'm closing this and we can open a new issue if the newer documentation is no sufficient.
