### ISSUE TITLE
Home Page Refresh

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#251]
The home page needs an updating, not sure what, but I like these graphics

![image](https://user-images.githubusercontent.com/1503976/235948563-6620c633-1be0-4b64-9e8d-3687e05dfa56.png)

![image](https://user-images.githubusercontent.com/1503976/235948645-08d9cf46-7220-402e-979f-cc653a37493d.png)

**Comment by gregnewman** [comment]
We now have a new home page, closing
