### ISSUE TITLE
site-docs search bar

### ISSUE THREAD

**Issue by alandefreitas** [cppalliance/temp-site#255]
The search bar is disabled in pages like

https://www.boost.revsys.dev/doc/user-guide/

Maybe it's just out of date. 

I don't know where the content comes from to boost.revsys.dev, but the docs are being sent to buckets from cppalliance/site-docs and cppalliance/boost. They work fine in the previews, for instance:

https://45.site-docs.prtest2.cppalliance.org/user-guide/index.html

**Comment by williln** [comment]
@frankwiles forcing the content type didn't seem to work. 

This is a truncated example of what the cached value looks like (from inside the dev pod): 

```
In [15]: static_cache.get("static_content_doc/user-guide/")
Out[15]:
(b'<!DOCTYPE html>\n<html lang="en">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width,initial-scale=1">\n    <title>User Guide :: Boost Site Docs</title>\n    <link rel="canonical" href="https://antora.cppalliance.org/user-guide/index.html">\n    
...
\n<script src="../_/js/search-ui.js" id="search-ui-script" data-site-root-path=".." data-snippet-length="100" data-stylesheet="../_/css/search.css"></script>\n<script async src="../search-index.js"></script>\n<script async src="../_/js/vendor/tabs.js" data-sync-storage-key="preferred-tab"></script>\n\n  </body>\n</html>\n',
 'text/html')
```

This is the bit that isn't loading: `<script async src="../search-index.js">`. I'm not sure how all of this works behind the scenes -- is the problem that S3 is serving the HTML file and we just can't access the MIME type of the JS files that are being served as well? Here is the PR I merged: https://github.com/cppalliance/temp-site/pull/328
