### ISSUE TITLE
News models

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#273]
The goal is to be able to have several different types of News items that can be displayed differently on the site (likely on `/news/`) 

The types are: 

- video
- blog post
- news / announcement
- link
- poll

We will have a posting form/interface on the site for logged in users (likely restricted to a certain Group, but that can be done in a later ticket) so the Django admin won't be the primary UI for people on this FYI. 

There are really two ways to model this.  One `News` model that has all of the various fields (and related model for poll questions/votes) or we build a separate model for each type and aggregate them only on the display view. I think we want to do the later. 

Each will need these fields: 

- title
- optional description
- publish datetime (date the news goes live, defaults to now)
- author FK

Then video obviously needs a video URL, probably a key frame image. 

Polls will need a M2M on questions and who voted.  Only logged in users will vote.  

Rough wireframe idea of how things will display: 

![CleanShot 2023-05-09 at 14 47 40](https://github.com/cppalliance/boost.org/assets/144159/bb25b100-b613-42f9-9245-64d776f2c531)

**Comment by nessita** [comment]
The backend work for this feature is complete (for a first iteration). Next step would be working on the visuals and UI.
