### ISSUE TITLE
"older version" disclaimer on every relevant page

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#282]
On the Libraries and every Library page, when the currently selected version is anything other than the latest version, we need a new user interface element which clearly indicates that the user is viewing an older version of the Boost libraries. We might also include the date of that release, and an unobtrusive link to where that release can be obtained (one of our interior Releases pages).

One way to achieve (2) is to put an "admonition" at the top of the page:

![image](https://github.com/cppalliance/boost.org/assets/1503976/fa29f89d-c4b4-46e2-94fa-ce2aea1c8c87)

Alternatively

![image](https://github.com/cppalliance/boost.org/assets/1503976/da5fc5d5-399b-428e-a801-c4bacc05813f)

The current website does this:

![image](https://github.com/cppalliance/boost.org/assets/1503976/bfc10bee-4c7f-4466-b654-bbb8b6f4eded)

but telling the user to "click" feels a bit dated :)

I think having something go all the way across the page would probably be best (i.e. a thin horizontal partly colored strip with an icon, some text, and a link or two in it).

**Comment by williln** [comment]
@gregnewman Will you need some data from the backend to key off of for this field? I think right now, the `version` selected is being returned, but not whether that version is the most recent. Let me know what's easiest for you and I can get that set up.

**Comment by williln** [comment]
Chatted with @gregnewman and reassigning to me -- should be able to finish this week.

**Comment by williln** [comment]
@vinniefalco We haven't implemented the `master` and `develop` branches in the Version drop-down yet, but when we do, will you want a message like this on those screens too? In that case it wouldn't be "an older version of boost," it would be "an unreleased version" or something similar.
