### ISSUE TITLE
Version Filter dropdown has the wrong size and is missing at least some filler versions (1.82.0, 1.81.0, 1.80.0 and so on)

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#300]
![image](https://github.com/cppalliance/temp-site/assets/1503976/2fd008b6-e3c6-4379-8372-ee139abb8cf9)

**Comment by williln** [comment]
@vinniefalco I can't see the screenshot on this one anymore -- is this issue still something that needs to be addressed?

**Comment by vinniefalco** [comment]
I guess its fine
