### ISSUE TITLE
Site docs have non-relative links

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#302]
This likely worked at some point, but with the multiple buckets in play all links need to be relative.  These here on the the User Guide (specifically https://www.boost.revsys.dev/doc/user-guide/) are broken

![CleanShot 2023-05-11 at 04 22 33@2x](https://github.com/cppalliance/temp-site/assets/144159/cd1bf293-959c-4898-8267-783af443e80c)

**Comment by gregnewman** [comment]
@frankwiles the embedded image is gone. is this still an issue?

**Comment by frankwiles** [comment]
No I think this is resolved, at least in the User guide.  There may still be some library docs that internally have non-relative links which might be broken but we'll just have to let those get discovered I think.
