### ISSUE TITLE
Title / metadata need setting

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#308]
The page title should be at least "Boost Libraries" for the home page.

If we can also adjust the title for the current page (e.g. "Boost: Libraries", "Boost: Math", "Boost: Learn" and so on or whatever is best practices, that would be great.

**Comment by DoumanAsh** [comment]
To set it you need to specify title in every page that is extended using `base.html`

```
{% extends "base.html" %}

{% block title %}My super Boost title{% endblock %}
```

**Comment by DoumanAsh** [comment]
Well, seems like you rely on docker so it should be very easy to prepare dev environment, so I could do it.

**Comment by vinniefalco** [comment]
Instructions are here: https://github.com/cppalliance/temp-site#readme

**Comment by gregnewman** [comment]
Page titles have been fully reworked
