### ISSUE TITLE
Page margins too tight in the nav area

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#309]
![image](https://github.com/cppalliance/temp-site/assets/1503976/769f23e3-57d2-43a7-accd-4e9ec67e51e5)

**Comment by gregnewman** [comment]
Please tell me what size your browser is (you can open the inspector and
resize to see the size)

**Comment by vinniefalco** [comment]
![image](https://github.com/cppalliance/temp-site/assets/1503976/5068516b-22b7-493f-afa6-fd4f7207a936)

**Comment by gregnewman** [comment]
Fixed in PR #357
