### ISSUE TITLE
Dark mode scrollbars need a restyling

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#312]
The default scrollbars are bright in dark mode and ruin the aesthetics.

**Comment by gregnewman** [comment]
I wouldn’t not suggest trying to do anything about default browser
functionality.  Reminds me of the Flash days.

**Comment by vinniefalco** [comment]
But adjusting scrollbar colors is very well supported and that vertical white scrollbar in dark mode ruins the thing. GitHub changes the scrollbar for Dark Mode why can't we? Is Microsoft better than us? 

![image](https://github.com/cppalliance/temp-site/assets/1503976/5f6b6f08-a82a-4499-9464-fe6f093ad47b)

**Comment by vinniefalco** [comment]
Wow its amazing what a different the scrollbar makes in darkmode. Before, it was like an ugly lightbar taped to the side of the window. Now it is sleek and elegantly incorporated into the page like it belongs there.

The new bar is missing some behaviors though. When you hover or click on the thumb it needs to change color (hover and click have separate visuals). Try it on https://github.com and compare.

The up and down buttons at the ends of the scrollbar also need feedback on hover and click. Can we just copy github's CSS and apply a hue/saturation or colorize to the RGB values to match our Style Guide for dark mode?
