### ISSUE TITLE
Help page

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#315]
Pressing the top nav help button

![image](https://github.com/cppalliance/temp-site/assets/1503976/e7a146ca-be3b-4b38-a434-20712eb8140f)

should navigate to the "Help" page: /help.html

This page will simply be a single-page rendered Asciidoc file that comes from some folder in the site-docs repo. For now we can just make it an empty HTML page that has the site header and footer with the text "Under construction" in the body.

Don't forget to delete the old content / images that came from Grain & Mortar.

**Comment by frankwiles** [comment]
@vinniefalco need to know the exact path to the asciidoc page.

**Comment by vinniefalco** [comment]
@alandefreitas we need to make a dir in the site-docs repo to hold the loose pages

**Comment by vinniefalco** [comment]
@frankwiles master/develop branch in this directory of this repo:

https://github.com/cppalliance/site-docs/blob/master/site-pages/help.adoc

We will put all the other loose pages there too like "privacy.adoc", "terms-of-use.adoc" and so forth.

**Comment by frankwiles** [comment]
Sorry I should have been more clear, I need to know the rendered doc in S3.  Would that end up in `/site-docs/site-pages/help.html` once it's generated? I don't see `site-pages` anywhere in the current develop folder.

**Comment by vinniefalco** [comment]
There's no rendered doc in S3, you will need to run Asciidoc as part of the building of static pages... and have the result inserted into the page using Django templates or whatever, so it has the header and footer and all that.

**Comment by gregnewman** [comment]
Has this been done so I can hook up the link?

**Comment by alandefreitas** [comment]
help.adoc is in the bucket: https://github.com/cppalliance/site-docs/actions/runs/5007580621/jobs/8974371297#step:7:13

**Comment by vinniefalco** [comment]
it puts the asciidoc in the bucket or else it gets the hose again
