### ISSUE TITLE
Clicking the search button should give focus to the edit box

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#320]
When the search edit box appears after clicking the button it should be given focus and the caret should be placed inside

Incorrect:
![image](https://github.com/cppalliance/temp-site/assets/1503976/83a61edd-94c4-455b-8adb-a03c7329b35c)

Correct:
![image](https://github.com/cppalliance/temp-site/assets/1503976/9431263e-6b2f-4aa0-ab40-48c144b3ec5d)

**Comment by gregnewman** [comment]
Fixed in PR #357
