### ISSUE TITLE
UI hover and feedback on Learn card links

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#322]
These links need hover state and cursor change
![image](https://github.com/cppalliance/temp-site/assets/1503976/98b46f51-a07c-4f58-b0ff-932a67c0ff9b)

**Comment by gregnewman** [comment]
If I recall, @frankwiles has the entire card linking to them the location and if so and you want hovers on these then we need to link each line to the same place.

**Comment by vinniefalco** [comment]
I think I edited the links to be correct, i.e. they now have the right text and link to the proper section in the docs.

**Comment by gregnewman** [comment]
Done in PR #357
