### ISSUE TITLE
Animation consumes too much CPU

### ISSUE THREAD

**Issue by Lastique** [cppalliance/temp-site#332]
The animated logo on the right half of the screen at https://boost.revsys.dev/ causes excessive CPU consumption. Please, remove the animation.

The logo also wastes too much space, so please consider reducing its size or completely removing it.

Kubuntu 22.04, Firefox 113.0.

**Comment by vinniefalco** [comment]
> The logo also wastes too much space

Are you referring to this logo?

![image](https://github.com/cppalliance/temp-site/assets/1503976/72f822b7-b3f4-4a8f-805d-f746fc2db33a)

**Comment by lockywolf** [comment]
I think, this issue is about a weird non-selectable element on the right that is occupying a lot of space, and seemingly brings little value:

![image](https://github.com/cppalliance/temp-site/assets/2077025/1b546330-654e-42d1-b309-bfbce8f2dfe3)


I would like to ask for removal of all animation from the website.

**Comment by gregnewman** [comment]
These animations will be replaced.

**Comment by Lastique** [comment]
On May 12, 2023 4:48:46 AM Lockywolf ***@***.***> wrote:

> I think, this issue is about a weird non-selectable element on the right 
> that is occupying a lot of space, and seemingly brings little value:
>
> ![image](https://github.com/cppalliance/temp-site/assets/2077025/1b546330-654e-42d1-b309-bfbce8f2dfe3)

Yes, exactly.

> I would like to ask for removal of all animation from the website.

Agreed.

**Comment by Lastique** [comment]
On May 12, 2023 4:53:23 AM Greg Newman ***@***.***> wrote:

> These animations will be replaced.

Not "replaced" - remove, please.

**Comment by gregnewman** [comment]
Animations have been removed.
