### ISSUE TITLE
Make library documentation versioned and preserve URL structure

### ISSUE THREAD

**Issue by Lastique** [cppalliance/temp-site#333]
The URL with the list of libraries (https://www.boost.revsys.dev/libraries/) should include a Boost release number, like the original website (e.g. https://www.boost.org/doc/libs/1_82_0/). It may be also a good idea to include a drop-down list of Boost releases to switch between.

The inclusion of version in the URL is important to be able to post links to documentation for the specific Boost release version, for example, on StackOverflow.

It should also be possible to reference the latest release in the URL (e.g. https://www.boost.org/doc/libs/release/). This is useful for including links in library documentation. In fact, given that there are many links to documentation present in various library docs already, the URL should preferably have the same structure as the original website (barring the hostname, of course). This will allow to keep the URLs working.

**Comment by vinniefalco** [comment]
Yes that is all correct, and I would also add there needs to be a page in the site-docs (User Guide or Contributor's Guide) which explains the structure of these URLs because I am always forgetting. @PeterTurcan

**Comment by williln** [comment]
Quick update on some of the items in this issue: 

> The URL with the list of libraries (https://www.boost.revsys.dev/libraries/) should include a Boost release number, like the original website (e.g. https://www.boost.org/doc/libs/1_82_0/). It may be also a good idea to include a drop-down list of Boost releases to switch between.

This is now in place: https://www.boost.revsys.dev/libraries/  and on the details page: https://www.boost.revsys.dev/libraries/ There are some small bugs in links that are being addressed

> It should also be possible to reference the latest release in the URL (e.g. https://www.boost.org/doc/libs/release/). 

This is reflected in https://github.com/cppalliance/temp-site/issues/386 as well so it's coming! 

> given that there are many links to documentation present in various library docs already, the URL should preferably have the same structure as the original website (barring the hostname, of course). This will allow to keep the URLs working

Yes, we're going to make sure existing URLs don't break. That's not in place yet, but it's definitely on the radar.

**Comment by Lastique** [comment]
> > It should also be possible to reference the latest release in the URL (e.g. https://www.boost.org/doc/libs/release/).
> 
> This is reflected in #386 as well so it's coming!

Just to clarify, the "release" keyword in the URL I posted is not a branch or a tag; it doesn't exist in Boost git at all. The current website interprets this keyword as the latest Boost release version. This is unlike develop and master that are being discussed in #386.

**Comment by alandefreitas** [comment]
There's something wrong with the drop-down list when any version `<1.0.0` is chosen. The only library we have there is Boost.Python. I guess the data source is not reliable for such old versions. We might want to ignore these versions or think of an alternative.

**Comment by williln** [comment]
Quick update: 

- The request about `release` in the URL is duplicated in https://github.com/cppalliance/temp-site/issues/361 
- the library listing page/url now include the ability to filter by Boost version (this work was covered in other issues) 
- @alandefreitas I'm going to create a new issue for your bug about libraries in versions older than 1.0.0

Going to close this ticket.
