### ISSUE TITLE
Please provide RSS feeds

### ISSUE THREAD

**Issue by Lastique** [cppalliance/temp-site#339]
Please provide RSS feeds for news and, separately, only for Boost releases. RSS is useful for news aggregation in clients like Thunderbird on the user's side.

**Comment by williln** [comment]
Reference: 

- Existing news RSS feed https://www.boost.org/feed/news.rss 
- Existing downloads RSS feed https://www.boost.org/feed/downloads.rss

**Comment by williln** [comment]
@4down @frankwiles @sdarwin The RSS feeds for News and Releases have been added. 

- There is a link to the releases RSS feed from the Releases page and it includes all full releases
- There is a link to the news RSS feed on the News page, and it includes all published `Entry` objects 
- I checked the existing RSS feeds and tried to replicate what was already there 

Feel free to reopen this ticket or open a new ticket to request changes, but the basics should now be there.
