### ISSUE TITLE
Further nav-bar tightening in the vertical axis

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#340]
Based on feedback I think we need to further tighten the nav bar vertically. I propose:

* shrink the Boost logo further so the logo text has the same em-height as the nav text items
* further reduce the empty space above and below the nav text (i.e. bring the horizontal rule up more, and re-align the items above it)
* Increase the size of the avatar so the bottom reaches the horizontal rule and the top is only a couple of pixels away from the top of the page
* Trim the right end of the horizontal rule to fall short of the Join / Avatar, so that the avatar has room. Like this:

![image](https://github.com/cppalliance/temp-site/assets/1503976/9e2752b6-3844-4950-be03-143bcbd198c6)

And I am not sure how it will turn out but I would like to experiment with doing the same thing on the left side but with the logo image instead of the avatar:

![image](https://github.com/cppalliance/temp-site/assets/1503976/cb2af292-ccd1-4724-b9b2-cf641fdc1969)

**Comment by vinniefalco** [comment]
Also if it is not computationally expensive can we try putting a 4 to 8 pixel fade under the horizontal rule? When the site is scrolled I would like the contents to fade out in opacity as it goes under the nav bar.

**Comment by gregnewman** [comment]
I tightened this up but have to create a fade still
