### ISSUE TITLE
Warning / Danger for unmaintained libraries

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#341]
we chould put a "warning" border around a library that hasn't been touched the last 2 release. And a "danger" border if it hasn't been touched in the last 6 releases (or so).

**Comment by pdimov** [comment]
I'd rather not. This can be communicated, but in a more subtle manner.

**Comment by vinniefalco** [comment]
How about a low-contrast, tasteful cobweb in the corner of the card?

![image](https://github.com/cppalliance/temp-site/assets/1503976/42e982e1-cc94-4a5d-b115-7ddb306be4c0)

**Comment by pdimov** [comment]
If two releases without changes is the criterion, more than half of my libraries would be cobwebbed.

**Comment by vinniefalco** [comment]
```
if( release_count_ > 2 && author != "Peter DImov" )
  bCobweb_ = true;
```

but yeah, I'll close this :)

**Comment by vinniefalco** [comment]
@pdimov if you have ideas on how to communicate it diplomatically, please open an issue
