### ISSUE TITLE
Flat list of libraries

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#342]
There should be a choice to view all libraries not as cards but a simple list that shows everything each on its own single line in a tabular format. C++ version, age, and categories can be right-justified columns in addition to the name.

**Comment by williln** [comment]
Closing as complete: https://www.boost.revsys.dev/libraries/mini/ 
<img width="1056" alt="Screenshot 2023-06-20 at 12 22 26 PM" src="https://github.com/cppalliance/temp-site/assets/2286304/1405050a-2121-449c-9ba7-1506b0681353">
