### ISSUE TITLE
Learn Page Illustrations

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#367]
The learn page illustrations need improvement. The "Release Process" card is going away so we only need User Guide, Contributor Guide, and Formal Review. I have attached the latest iterations of this artwork. This issue is for discussion and iteration on the illustrations before final approval and merge.
[Boost - Website Illustrations - v3.pdf](https://github.com/cppalliance/temp-site/files/11510367/Boost.-.Website.Illustrations.-.v3.pdf)

Preview:
![image](https://github.com/cppalliance/temp-site/assets/1503976/ffd23614-7460-4c0d-b762-04160661441a)

**Comment by chadmadeit** [comment]
@vinniefalco — Please find attached the updated illustration for User Guide with the Boost logo removed, and an updated sketch for Formal Reviews based on your feedback. Let me know if you have any edits before I create the full version.

![Boost - Website Illustrations - v4](https://github.com/cppalliance/temp-site/assets/17732200/8080d7fd-b354-462b-b27a-b412bf388050)

**Comment by vinniefalco** [comment]
Oh I like that direction! Wondering about those faceless heads though...

**Comment by chadmadeit** [comment]
If you want, I can add simple faces to each of them @vinniefalco

**Comment by vinniefalco** [comment]
if we are going to keep it in the style of Contributor Guide then we need to make the characters in that sketch more abstract. Otherwise it will clash with the existing style.

**Comment by chadmadeit** [comment]
@vinniefalco — Once fully rendered the characters in the jury artwork will match those in the Contributor Guide. Are you needing me to revise the sketch further or do you want to move forward with rendering the artwork?

**Comment by vinniefalco** [comment]
Lets render

**Comment by chadmadeit** [comment]
@vinniefalco — Please find attached the fully rendered version of the Boost Formal Reviews illustration and let me know if you need anything else for now!

<img width="1596" alt="Screenshot 2023-06-12 at 11 31 33 AM" src="https://github.com/cppalliance/temp-site/assets/17732200/5ae9a96e-744b-473c-b069-785241bb7009">

**Comment by vinniefalco** [comment]
no love for redbones or albinos?

**Comment by vinniefalco** [comment]
The guy mounting the defense could look better, maybe lose the book and use both hands like this:
![image](https://github.com/cppalliance/temp-site/assets/1503976/9a659b9f-aa1a-4eae-8788-8cb718b59eca)

**Comment by chadmadeit** [comment]
Hello @vinniefalco — Sounds good I will make one of the jury members albino and adjust the hands on the attorney. Can you please clarify what you want to see for "redbone"? Thanks Vinnie!

**Comment by vinniefalco** [comment]
Sorry... I was mostly joking about albinos and redbones. A redbone is someone who is half black and half white (i.e. skin tone in between black and white).

**Comment by chadmadeit** [comment]
@vinniefalco — Please see the attached updated illustration. I updated the attorney's arms/hands and added more variation in the jury's skin tones. Let me know what you think!

<img width="864" alt="Screenshot 2023-06-21 at 11 13 58 AM" src="https://github.com/cppalliance/temp-site/assets/17732200/b70349fe-9f24-4f71-9952-87010c251cd3">

**Comment by gregnewman** [comment]
The learn page has all of Bob's illustrations so closing this issue.
