### ISSUE TITLE
Download Boost button

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#368]
We are designing a "Download" button for Boost. This issue is for discussion and iteration on the illustration before final approval and merge.
[Boost - Button Designs- v1.pdf](https://github.com/cppalliance/temp-site/files/11510426/Boost.-.Button.Designs-.v1.pdf)

Preview:
![image](https://github.com/cppalliance/temp-site/assets/1503976/e2704f73-cedb-4813-b5d2-919e705fddad)

**Comment by chadmadeit** [comment]
@vinniefalco — I have attached the separate button images as requested. Let me know if you need anything else for this for now.

![Boost - Button Designs- v1A](https://github.com/cppalliance/temp-site/assets/17732200/d63cee36-4610-43a8-b522-7009645f488c)
![Boost - Button Designs- v1B](https://github.com/cppalliance/temp-site/assets/17732200/e2a95ec8-57cb-4b0f-a238-c0e8b9ed0322)
![Boost - Button Designs- v1C](https://github.com/cppalliance/temp-site/assets/17732200/9608160e-bc34-4d27-8baf-9aadc2787677)
![Boost - Button Designs- v1D](https://github.com/cppalliance/temp-site/assets/17732200/d532d0ff-c6d9-4053-bbfe-d8a06f25a3df)

**Comment by vinniefalco** [comment]
Well I think we wanted to keep only the ones with the package and remove the ones with the B logo because we only use the logo on the top nav
