### ISSUE TITLE
Boost Release Illustration

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#369]
We need an illustration that represents the physical embodiment of a Boost release. This will be used on the Releases page, in iconography, and in Twitter images. The goal here is a repeatable and instantly recognizable icon which says "You can get a release archive here." This is the prior artwork:

![image](https://github.com/cppalliance/temp-site/assets/1503976/3a7a38c4-d6fb-4cd0-825a-c25a6b0d9f0a)

![image](https://github.com/cppalliance/temp-site/assets/1503976/02b299c7-0777-498e-8095-fd37f3b9ecf3)

![image](https://github.com/cppalliance/temp-site/assets/1503976/cb9a0b2e-5eca-4cb7-a40c-d1f4f0ebcb1e)

And this unlicensed image from the Releases page:

![image](https://github.com/cppalliance/temp-site/assets/1503976/97a4b724-eed5-44d8-a878-fbe7a30b8ac3)

We just need the box itself not the surroundings. We will need a full color and detail image, and then we will need a scaled down abstract version of it (like what is in the download buttons).

**Comment by chadmadeit** [comment]
@vinniefalco I have attached the full sized detailed image of just the box without the surroundings. Let me know what you would like to do with the version number. I will also work on the scaled down abstract icon version.

![Boost - Release Box - Full](https://github.com/cppalliance/temp-site/assets/17732200/806eb71f-ba5a-442f-99bb-eb847942caa1)

**Comment by vinniefalco** [comment]
I'm not feeling that at all
