### ISSUE TITLE
Boost Beta Homepage Wireframe Implementation

### ISSUE THREAD

**Issue by novoio** [cppalliance/temp-site#387]
Need to redesign Homepage according to the instructions and wire frame provided in the [document](https://docs.google.com/document/u/0/d/187Q6VVBrm5KsTTY-NuAFBXVl6TL0jLBrAKrr2cnPFXk/mobilebasic#cmnt6).

Tasks to be completed:

- Convert the approved wireframe into a fully functional homepage.
- Implement the necessary backend functionality and external integrations as outlined in the wireframe and discussed during previous discussions.
- Incorporate dynamic content and interactive elements where applicable.
- Apply styling and design elements consistently throughout the page.
- Ensure responsiveness and compatibility across different devices and screen sizes.

**Comment by frankwiles** [comment]
@novoio just create a new URL path `/new-homepage/` (or something) and create new view basically copying `HomepageView` (from here https://github.com/cppalliance/temp-site/blob/main/ak/views.py#L7-L13) and use a new template.  Let me know if you have questions.
