### ISSUE TITLE
Login/Signup Features

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#39]
The want their users to login primarily with Github or Google.  With the last resort being we create a username/email based account for them directly in the system. 

We should: 

- [x] Drop a cookie or localstorage in the browser to track WHICH service they used to login last time and adjust the login display to mention that.  So a user doesn't register with Github and come back and re-register with Google because they forgot about the first time. 
- [x] If we do not get an email from Github or Google directly, we need to prompt the user for one after signup and require it to continue.  
- [ ] Send the user an email at that email with which (Github/Google/email) choice they made so they have a record in their email history at least

**Comment by williln** [comment]
@gregnewman Frank and I talked and it seems like it will make the most sense to set a localstorage using JS, and since you'll also be making the call on what to do based on the value of the localstorage, it makes more sense for you to take this.

I'm not sure if we still want to send an email, but if there are side effects that the backend should take, let me know!

**Comment by gregnewman** [comment]
I'm going to set localstorage in login.html when the button is clicked.  If the user cancels or there is an authentication error I will clear localstorage in the respective templates.

**Comment by williln** [comment]
@4down The outstanding item on this ticket is: 

> Send the user an email at that email with which (Github/Google/email) choice they made so they have a record in their email history at least 

Right now, I don't think we are sending any email at all when the user completes registration. Do we want to?

**Comment by gregnewman** [comment]
I didn't see your message here from last week @williln can this be closed. this is a very old issue.

**Comment by williln** [comment]
@gregnewman  Let's bring it up in the meeting to see if they want that last feature and if not, we can close.
