### ISSUE TITLE
Library Card with wrapped categories is not spaced elegantly

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#390]
![image](https://github.com/cppalliance/temp-site/assets/1503976/d13eccad-758c-4ec1-a78d-a39e7a35a290)

**Comment by gregnewman** [comment]
I tested this out and see GIL has a lot of tags. The wrapping looks good.

![CleanShot 2023-10-20 at 10 43 09](https://github.com/cppalliance/temp-site/assets/2026/b7be65c2-84d6-4b14-9f31-6c205ed21f84)
