### ISSUE TITLE
Content should be more condensed

### ISSUE THREAD

**Issue by jepessen** [cppalliance/temp-site#393]
Hi.
In attachment you can find a screenshot of the site in my 2560x1440px monitor.

In my opinion the content of the site should be a bit more condensed; there's too much wasted space in the first part of the site. By following the UX design rules, most important sections of the site should be right in fron of eyes of the user; instead I need to scroll if I want to see reviews and news.

I suggest to move those section in the upper part (maybe in a lateral view). Forum is a bit less important in my opinion and it can take the bottom part of the site, it's ok for me to scrool the page in order to check forum content.

![image](https://github.com/cppalliance/temp-site/assets/13927767/29845e68-ba14-4254-b407-02d478189b7d)

**Comment by vinniefalco** [comment]
I agree with you. But I have a different idea how about if we just throw out that home page entirely and replace it with something amazing being developed by @joaquintides  :)
