### ISSUE TITLE
Ascii doc static content rendering

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#394]
We're not going to be doing Markdown any longer and instead be doing Asciidoc to keep things consistent with the documentation format. 

We need the following features: 

- [x] Ability to map a URL path to paths inside of an S3 bucket.  This is exactly like the docs related code, but in this case the content is NOT rendered and needs to be rendered. 
- [x] Ability to map a URL path to paths inside of this repository (i.e. `./content/help.adoc`)
- [x] Content should be rendered using the Ruby asciidoc utility [install instructions for Docker container](https://docs.asciidoctor.org/asciidoctor/latest/install/linux-packaging/)
- [ ] Content should be rendered async in a Celery task 
- [x] Rendered content should be cached both in the database and Redis
- [x] Code to bust the cache of a single path (i.e. `/help/` or `/help/*` 
- [x] Code to bust the entire cache of ascii doc files (database and Redis) 

Replaces #12 
Related to #315

**Comment by williln** [comment]
Gist of what the HTML for a converted file looks like: https://gist.github.com/williln/8de21ea28402f88a903c122405c1abf5

**Comment by williln** [comment]
@frankwiles 

> cached both in the database and Redis

In the view, would the process be like this for asciidoc files? 

- If user requests static content and it's asciidoc, first we check the redis cache. 
- If not there, then we hit S3 
- If not there or not processable, we check the database using the s3 key 
- if not there, 404

**Comment by frankwiles** [comment]
Based on that GIST above, we're going to need to parse it a bit with something like BeautifulSoup to remove the outer HTML elements, most likely only keeping the children of the `<body>` tag.  We'll rely on the site's Tailwind CSS to handle what it spits out in the `<style></style>` tags don't do you think @gregnewman ?

**Comment by frankwiles** [comment]
Actually @williln I'm thinking: 

- User requests static content and it's asciidoc, check Redis cache
- If not there, check database
- If not there, check S3, process it.  Store in Redis AND the database and return it to the user
- If not there, 404 

We also are going to need some way to expire this database cache on some sort of schedule, otherwise rendered to the database items would never update. 

At this point, you're probably asking yourself "Why the database at all?".  My thinking is, it's somewhat expensive to render asciidoc (compared to everything else we're doing) and the pages are unlikely to change super frequently.  So it's VERY likely we'll have situations where a page is rendered, cached for say an hour, but is only typically accessed every 4-6 hours.  Which means we're rendering it 4-6 times a day... without any changes.  So think of the DB cache as the actual cache of the "asciidoc -> html" process and Redis is just there so the database doesn't fall down when one of these pages ends up on HackerNews.

**Comment by gregnewman** [comment]
Yes, I agree @frankwiles

**Comment by frankwiles** [comment]
One idea for expiring the database content is to store with the database cache the S3 last modified time of the asciidoc and then on ANY checks that fall through to the database we fire a separate celery task to compare the last modified time.  If it's different we can kick off a re-render/re-cache task.

**Comment by williln** [comment]
> we're going to need to parse it a bit with something like BeautifulSoup to remove the outer HTML elements, most likely only keeping the children of the <body> tag.

Yeah, I'd figured that out but kept the existing PR simple. That'll come tomorrow, probably.
