### ISSUE TITLE
Need Antora playground

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#395]
Can we get a playground repo for your Antora docs or perhaps access to mess with one of your library's docs repos @vinniefalco ? 

Need this to have quick dev / test cycles on the shared header.

**Comment by vinniefalco** [comment]
I believe this already exists, you want to edit the "ui bundle" and there is a command "gulp preview" which runs a local webserver and updates in real time with your changes.

**Comment by frankwiles** [comment]
@gregnewman I think that works yes?

**Comment by gregnewman** [comment]
Yes, that should work.
