### ISSUE TITLE
Shared Nav Plan Decision Needed

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#396]
So @vinniefalco we have two options for the shared nav header between the site and docs/other content repos. 

## Option 1 - Load JS/CSS remotely 

This would work be having a blank/empty markup element `<nav id="boost-shared-header"></nav>` or something similar in the Antora UI templates.  Along with tags to load a bit of JS from our site.  

This would then render the nav and allow for the user's browser to call back to the site to determine logged in status.  Should work even on remote sites if there was ever a need for fancy-boost-docs.com or whatever.  

### Pros 

- Quick updates of all docs when changes to nav are deployed (i.e. just browser cache time which we'll set low)

### Cons

- Makes the in browser payloads a bit bigger as there would be additional JS and duplicate Tailwind CSS being loaded on docs pages

## Option 2 - Github Action driven

We create a Github Action that is called when changes to the nav are merged in which would create PRs on all docs repos to pull the changes into them. 

### Pros

- Small payloads

### Cons

- Might be weeks before some repos merge the change 
- Requires close coordination of GH Actions, repository lists, etc. 

Which way would you like us to head? I think Option 1 is the best but wanted to confirm before we went too far down the road. 

## Option 3 - Keep canonical copy of nav markup in antora-ui

This idea was suggested by Vinnie. 

## Option 4 - Reverse Vinnie 

Same as Option 3, except we keep the canonical copy in THIS repo and populate it to antora-ui when it changes. This is somewhat simpler on our end to manage.

**Comment by vinniefalco** [comment]
The thing I don't like about "auto-publish changes" is that now we have the same file in two different repositories. In my proposal the file would only exist in the site-docs repository, and it would get copied to an s3 bucket. Maybe there is a way that the antora-ui build process could retrieve the file from the source repo?

**Comment by vinniefalco** [comment]
Lets just try it your way, the expedient way, and that will be better than nothing. And we can see how it plays out and then decide if we have to change it further.

**Comment by frankwiles** [comment]
I understand the concern, but it's going to get copied in one direction or another or we have to code up some really weird (form a Django perspective) S3 powered template loader code.  

We'll try it `temp-site -> antora-ui` and see how it goes as a first stab @gregnewman

**Comment by gregnewman** [comment]
Since this is implemented I'm closing this issue @frankwiles

**Comment by vinniefalco** [comment]
I hope we didn't choose 2

**Comment by gregnewman** [comment]
We did not @vinniefalco
