### ISSUE TITLE
Titles should have links

### ISSUE THREAD

**Issue by miguelportilla** [cppalliance/temp-site#401]
The title sections "User Guide" and "Contributor Guide" and their subtexts, should have links to the respective pages. The "Contributor Guide" subtext, "This is how you can help" is styled with an incorrect color.

![image](https://github.com/cppalliance/temp-site/assets/1524671/fe2a28aa-2ca1-4fde-a047-4eedfae76581)

**Comment by gregnewman** [comment]
These are now links
