### ISSUE TITLE
Bad Request Error when Access is Denied during GitHub Login

### ISSUE THREAD

**Issue by louistatta** [cppalliance/temp-site#403]
When attempting to log in to the site using GitHub login, if the user denies access, they are redirected to a "Page Not Found" error page. This behavior can be observed through the following example URL: [Link](https://www.boost.revsys.dev/accounts/github/login/callback?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied&state=lBOQgYzNafKA)

Click on the "Login with GitHub" button.
On the GitHub authorization page, deny access to the site.
The user is redirected to a "Page Not Found" error page.

**Comment by williln** [comment]
The fix I put in worked locally, but when deployed, gives this error: 

<img width="1065" alt="Screenshot 2023-07-12 at 11 50 42 AM" src="https://github.com/cppalliance/temp-site/assets/2286304/8043181a-d200-48c7-a274-e39c90d609df">

The url is `vsys.dev/accounts/github/login/accounts/github/login/accounts/github/login/....`, repeating like that, so my solution of redirecting has apparently caused a redirect loop.

**Comment by williln** [comment]
We've tested the login process a lot lately, so I am going to close this and assume it's fixed. We can reopen if needed.
