### ISSUE TITLE
Libraries search drop-down menu unusable

### ISSUE THREAD

**Issue by miguelportilla** [cppalliance/temp-site#405]
![image](https://github.com/cppalliance/temp-site/assets/1524671/9fddd057-0dad-4cd5-9e4c-821a8272e056)

The Libraries Search drop-down menu appears when the Search area is clicked but disappears quickly afterward, not allowing the user to make a selection.  If a selection is made, it does not seem to have an effect.

**Comment by gregnewman** [comment]
@miguelportilla this screenshot looks to me like something is wrong in your browser.  Can you tell me what browser you are using?  Do you have javascript disabled?

The size of the cards tell me that the css is not properly loading for you and also you should get a command palette when you click into the search like in this screenshot.

<img width="1011" alt="CleanShot 2023-05-31 at 19 18 54@2x" src="https://github.com/cppalliance/temp-site/assets/2026/475c434b-c912-4a52-97ba-7d1b4f6469bf">

**Comment by miguelportilla** [comment]
@gregnewman The screenshot is taken using the Brave browser, I have verified Javascript is enabled.
