### ISSUE TITLE
Overlapping of selected text selection boxes

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#423]
![image](https://github.com/cppalliance/temp-site/assets/49487079/1c9a54fe-6aaf-43cb-82f7-7a65fd44d0db)

This is likely a result of adding in Tailwind and maybe a mixing of prior styles with new ones.  Regardless, I believe this is an issue of the line-height being set too tall for the font size.

**Comment by gregnewman** [comment]
Where are you seeing this @4down ?

**Comment by 4down** [comment]
@gregnewman - It's happening almost everywhere that I try it.

<p float="left">
  <img width="300" align="top" src="https://github.com/cppalliance/temp-site/assets/49487079/150522d1-dc53-41a9-9710-c3b0e866ef44">
  <img width="300" align="top" src="https://github.com/cppalliance/temp-site/assets/49487079/4b13df29-8eb6-4eb3-a8c7-732e2f8fe7f9">
</p>

<p float="left">
  <img width="300" align="top" src="https://github.com/cppalliance/temp-site/assets/49487079/51f4c8a9-7651-49c2-9a76-ad6781cb3c5c">
  <img width="300" align="top" src="https://github.com/cppalliance/temp-site/assets/49487079/a02ebb67-9f0b-4ed7-9d58-fd6be8e1e35b">
</p>

<p float="left">
 <img width="300" align="top" src="https://github.com/cppalliance/temp-site/assets/49487079/9ea619b2-f7a2-4a2a-9cf2-0598628134c7">
</p>

**Comment by gregnewman** [comment]
Can you get on a slack huddle with me in the morning to work through it together?  I’m EST.

**Comment by 4down** [comment]
@gregnewman Definitely.  Ping me whenever you're ready or to sync up on start time.  I'm CST, online by 8 my time.

**Comment by gregnewman** [comment]
@4down will do

**Comment by gregnewman** [comment]
Reviewing this issue @4down this is not an issue but how selection and css line heights work.  I don't see an issue with this behavior.
