### ISSUE TITLE
Local Dev Setup Issue: AWS keys

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#425]
AWS keys cannot be a requirement to build and run the site locally.  People who are contributing to the code can't all be given access as this poses a security risk at the least.

`{"message": "get_content_from_s3_error", "key": "favicon.ico", "bucket_name": "changeme", "s3_key": "/site/develop/favicon.ico", "error": "An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.", "function_name": "get_content_from_s3", "logger": "core.boostrenderer", "level": "error", "timestamp": "2023-06-05T16:53:16.838606Z", "exception": "Traceback (most recent call last):\n  File \"/code/core/boostrenderer.py\", line 50, in get_content_from_s3\n    response = client.get_object(Bucket=bucket_name, Key=s3_key.lstrip(\"/\"))\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/botocore/client.py\", line 530, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/botocore/client.py\", line 964, in _make_api_call\n    raise error_class(parsed_response, operation_name)\nbotocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records."}`

**Comment by gregnewman** [comment]
I do not think this is a requirement to have the keys @4down but you should at least have the key value pairs in your local .env vile.

**Comment by 4down** [comment]
@gregnewman Who can I reach out to in order to get the keys?  Thanks!

**Comment by gregnewman** [comment]
@4down for local dev you shouldn’t need them. But ping @frankwiles if for some reason you do.

**Comment by 4down** [comment]
The errors here seem to have been related to problems arising from #426 - after somewhat resolving those issues locally, this error message is no longer appearing and does not seem to prevent any ability of running the site locally.
