### ISSUE TITLE
Local Dev Setup Issue: docker commands failing

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#426]
Possibly related to this issue when first starting up the docker container:

> (temp-site-web-1) django.db.migrations.exceptions.InconsistentMigrationHistory: Migration account.0001_initial is applied before its dependency users.0001_initial on database 'default'

Here is the initial output for the **createsuperuser** command:

> docker compose run --rm web python manage.py createsuperuser
> [+] Building 0.0s (0/0)                                                                                                                                                                                                     
> [+] Creating 1/0
>  ✔ Container temp-site-db-1  Running                                                                                                                                                                                   0.0s 
> [+] Building 0.0s (0/0)                                                                                                                                                                                                     
> 
> You have 74 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): auth, db, forum, forum_attachments, forum_conversation, forum_member, forum_permission, forum_polls, forum_tracking, libraries, mailing_list, news, users, versions.
> Run 'python manage.py migrate' to apply them.
> Email address: test@test.com
> Traceback (most recent call last):
>   File "/venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
>     return self.cursor.execute(sql, params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> psycopg2.errors.UndefinedTable: relation "users_user" does not exist
> LINE 1: ..."."valid_email", "users_user"."display_name" FROM "users_use...

Continuing with the next steps in the setup doc, 

**makemigrations** fails with: 

> django.db.migrations.exceptions.InconsistentMigrationHistory: Migration account.0001_initial is applied before its dependency users.0001_initial on database 'default'.

**migrate** fails with the same message.

**just test** produces:

> FAILED users/tests/test_urls.py::test_signup_post - redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.

The local site does load and is running, but just the static HTML pages.  Libraries for instance fails due to the AWS key issue #425

**Comment by sdarwin** [comment]
What is happening, is that the mailman migrations are being run in the main database, which then interferes with boost database migrations, which breaks the configuration.

Consider how the mailman3 suite is designed. Here is a quote from their mailing list "But they don't connect to 1 database.  Each component has its own database".   

In the original design at least mailman core and hyperkitty would each have their own databases, even if they are on the same db server.

These products (mailman-core, hyperkitty, postorius) are somewhat complex in their own way, and keeping the structure they expect could help avoid db conflicts.

**Comment by 4down** [comment]
I was able to get around the issues above by removing the postgres DB from the docker container, going back to a commit roughly 4-5 weeks ago, spinning up docker where the process ran without error, and then jumping back to the latest commit.  

The issue is still not resolved, but this is a way around it for now.
