### ISSUE TITLE
Review text for emails being sent after news events

### ISSUE THREAD

**Issue by nessita** [cppalliance/temp-site#468]
Currently, there are 3 emails that are being sent after some news events occur (see issue #343). These are:

1. A new you submitted was approved by a moderator.
2. A new news entry was posted.
3. A new news entry was submitted and needs review/moderation.

This email sending logic is isolated in the `notifications` module in the `news` app (https://github.com/cppalliance/temp-site/blob/develop/news/notifications.py), and the email bodies are DRAFT and need a careful review and likely text tweaking.

**Comment by frankwiles** [comment]
They seem perfect to me.  Definitely good enough to launch with.  Thanks!
