### ISSUE TITLE
New Homepage commit data

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#473]
![image (4)](https://github.com/cppalliance/temp-site/assets/144159/7694e13d-c7b9-4fea-aeaf-b7776391b312)

For the code metric numbers on new homepage we have a couple of questions.  The items commits, open/new PRs, open/new Issues across time ranges makes sense.  Question is: 

Could we do Closed PRs and Closed Issues instead of "Active"? That is much easier to gather from Github, we can do active for sure but it's quite a bit more work to gather it from them (essentially crawling everything a bunch more)

- [ ] ~Need Slack API key to gather Slack messages~ (removed as it's not possible without Enterprise Account)
- [ ] Need JFrog API key and docs/link on how to gather
- [ ] Need Conan API key and docs/link on how to gather
- [ ] Need vcpkg API key and docs/link on how to gather
- [ ] Keep current display of numbers and we'll combine later

**Comment by frankwiles** [comment]
JFrog data can be retrieved without any authentication per Sam: 

```shell 
$ curl -X GET https://boostorg.jfrog.io/artifactory/api/storage/main/release/1.82.0/source/boost_1_82_0.7z?stats
$ curl -X GET https://boostorg.jfrog.io/artifactory/api/storage/main/release/1.82.0/source/boost_1_82_0.tar.bz2?stats
$ curl -X GET https://boostorg.jfrog.io/artifactory/api/storage/main/release/1.82.0/source/boost_1_82_0.tar.gz?stats
```

**Comment by frankwiles** [comment]
Removing Slack as it's only available on Enterprise Grid accounts per Sam.

**Comment by frankwiles** [comment]
We will keep the 3 different download numbers per Vinnie as it's not really a total even together because of Boost being distributed via other means like Linux distro packages.

**Comment by williln** [comment]
@4down We're not doing this, right? We can close this?

**Comment by 4down** [comment]
Yes - closing now. Thanks!
