### ISSUE TITLE
Social Login: If you have an email account, and try to log in with GitHub or Google, it reverts to "sign up" and won't complete 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#486]
Reported by @gregnewman in today's meeting.

**Comment by williln** [comment]
@gregnewman I can't reproduce this (maybe it was fixed with some of the allauth template changes earlier this week?). Can you let me know if you're still seeing errors with social login? If not, then I'll close this.

**Comment by gregnewman** [comment]
@williln I'll see if I can reproduce it again.

**Comment by gregnewman** [comment]
@williln what's happening is I have an account via my email address.  I tried to login with GitHub (and google) which reverts to "sign up" instead and never completes.

**Comment by williln** [comment]
@gregnewman Thanks for sharing more info about the conditions for the bug, I'll look into it!

**Comment by williln** [comment]
Closed by #598
