### ISSUE TITLE
Releases page: Make docs link version-sensitive

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#499]
The link on the Releases page should go to that release's docs. 

Questions for @4down: 

- The tags in GitHub go up to `1.82.0`: https://github.com/boostorg/boost/tags, but the docs in the `/archives/` folder in S3 only go up to `1.82.0-beta1`. What should happen in this case, where we have a release in the database that doesn't have valid docs in S3? 
- Is this the right URL pattern? `/doc/libs/boost_1_81_0/index.html`.

**Comment by williln** [comment]
@sdarwin Is it possible to have the docs for the current version also in S3, so the process for generating the link is consistent for all releases? We haven't talked about publishing the docs directly via this website, we've mostly focused on retrieving them from S3. I'm not sure what you mean by publishing the docs with a GUI or a script. (cc @4down @frankwiles -- one of you might have more insight into this process than I do). 

It sounds like we should have a more in-depth conversation about the process when a new version is released?

**Comment by williln** [comment]
FYI -- PR #500 includes a **placeholder** link to the current `boost.org` docs for the current release only, since those docs are not in S3 and there is some work to do to generate them; this way we still have a live link on the current release page, and not a 404 or no link at all.

**Comment by sdarwin** [comment]
> Is it possible to have the docs for the current version also in S3

Try now, I uploaded 1.82.0.

**Comment by williln** [comment]
@sdarwin Worked great, thanks! Updating my PR now.
