### ISSUE TITLE
footer needs a tweakin'

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#504]
Before:

![image](https://github.com/cppalliance/temp-site/assets/1503976/06a267ac-b6d0-4559-973d-52ebdb540cf1)

After:

![image](https://github.com/cppalliance/temp-site/assets/1503976/ad4c7437-97bb-4bca-b0ea-546b9470dc07)

**Comment by vinniefalco** [comment]
probably make that CPPA text a link too but keep it black (mustard on hover)

**Comment by gregnewman** [comment]
I'm taking this one because it will affect the footer I'm pulling into Antora too.

**Comment by gregnewman** [comment]
`text-lg` for the first line and `text-sm` for the second line

![CleanShot 2023-07-12 at 15 43 16](https://github.com/cppalliance/temp-site/assets/2026/8a56dc1e-2b00-4a4b-a82f-35fe524487ad)

**Comment by vinniefalco** [comment]
We already did it and merged it...
