### ISSUE TITLE
Libraries by Name needs a heading

### ISSUE THREAD

**Issue by vinniefalco** [cppalliance/temp-site#505]
When libraries are listed by name, the list needs a heading. For example "Libraries by Name"

![image](https://github.com/cppalliance/temp-site/assets/1503976/0937c1c0-e500-497d-acc0-9c9f40d80aaa)

**Comment by gregnewman** [comment]
We will need names on all Library list views @vinniefalco otherwise the content areas will jump when switching between them.  What would you like the titles to be for the three views?

1. Category
2. Cards
3. List

**Comment by vinniefalco** [comment]
Yeah that's good
