### ISSUE TITLE
Changes to user profile page 

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#506]
If logging into website with username/password, and then going to My Profile:  
- The "Password" link does not work.
- Email and username are not shown in the profile.  
- Cannot modify email or username in the profile.
- Many placeholder badges and stats appear. (perhaps this is intentional).

**Comment by vinniefalco** [comment]
The entire User Profile page is undesigned / unimplemented I believe.

**Comment by sdarwin** [comment]
Completed
