### ISSUE TITLE
Library view icon+buttons have incorrect light/dark hover/selected states

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#510]
![image](https://github.com/cppalliance/temp-site/assets/49487079/271d1c20-ae3e-4af2-8294-1abfa3a76f7e)
![image](https://github.com/cppalliance/temp-site/assets/49487079/899c9d1f-67c2-4a25-93fc-48b59975cb97)

The buttons need to get a good once-over to make sure light/dark + hover/selected states are all correct.

TBD: what colors to use.

**Comment by gregnewman** [comment]
@4down you can go back to the original issue in #421 to determine what I did.  Did not have any direction here.
