### ISSUE TITLE
rustywind Tailwind CSS class linter failed

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#530]
The message continues to show failed CI jobs in Github Actions. Not a high priority issue in itself. But when you attempt to deploy and the full CI process isn't able to proceed because lint failed, then it sort of becomes a blocker for other testing, so opening this issue.

```
rustywind Tailwind CSS class linter......................................Failed
```

**Comment by frankwiles** [comment]
@gregnewman I'm not familiar with rustywind at all.  What does it do for us? It seems to keep causing problems and wondering if it's more trouble than it is worth since I've never heard/used it before.

**Comment by gregnewman** [comment]
@frankwiles it cleans up the classes in the html template removing duplicates and sorting them to a certain extent.  I thought @nessita had removed it from the CI job after I suggested this only be used locally.  I use it locally before a push but it should NOT be used in the CI jobs because it's going to try to rewrite some html.

**Comment by gregnewman** [comment]
Assigning to myself to remove this in the morning and set it to manual for local use.

**Comment by frankwiles** [comment]
Awesome thank you!

**Comment by gregnewman** [comment]
Rustywind has been removed

**Comment by nessita** [comment]
> @frankwiles it cleans up the classes in the html template removing duplicates and sorting them to a certain extent. I thought @nessita had removed it from the CI job after I suggested this only be used locally. I use it locally before a push but it should NOT be used in the CI jobs because it's going to try to rewrite some html.

Sorry @gregnewman! From our chat I got the (wrong) impression that you rather wait a bit on the removal to debug the apparent race condition making the lint check fails, so I did not do it. On retrospective, I may have misunderstood!

**Comment by gregnewman** [comment]
@nessita not a problem at all.  It's gone now ;)
