### ISSUE TITLE
When no news are available, the invitation to submit news should mention that login is required

### ISSUE THREAD

**Issue by nessita** [cppalliance/temp-site#537]
When no news are available, and the user is not logged in, this screen is shown:
![image](https://github.com/cppalliance/temp-site/assets/124304/5b5b1d84-ab6b-47f9-a30c-f99d452eaf16)

The message `No news yet; consider submitting something!` should ideally invite the user to login so they have a "create news" button available. Otherwise the UI has no indication on how to submit a news.

**Comment by gregnewman** [comment]
@4down I'm grabbing this one, a quick fix
