### ISSUE TITLE
Social Auth profile photo

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#543]
When testing GitHub Social Auth it will show a 500 error if the profile photo fails to import.  That led to debugging S3, and I  discovered the following issues.

1. Authenticate using GitHub Social Auth with multiple users: User1, then User2, the User3. Each time, the profile photo was imported as `-profile.png`.  

```
https://s3.us-east-2.amazonaws.com/boost.org-cppal-dev-v2.media/profile-images/-profile.png
```

What should the name of the photo be?  Probably not `-profile.png`. It's causing an overlap or conflict where each new user overwrites the previous user's pic located at `-profile.png`.

 
2. Public access needs to be globally enabled on the bucket, and S3 ACLs must be enabled.  This error will appear otherwise:

```
An error occurred (AccessControlListNotSupported) when calling the PutObject operation: The bucket does not allow ACLs"
```

However, ACLs are a legacy not-recommended feature. Could the dependency on ACLs be removed? Something to think about. Not critical, not a priority.

**Comment by sdarwin** [comment]
- If a user changes their profile photo, the previous photo isn't deleted.  It probably should be deleted. Since that will just be an accumulation of unused files.

- If a user uploads a photo with the same image name as another user, such as photo1.jpg, it overwrites that file.   Now both users have the same photo1.jpg.

**Comment by frankwiles** [comment]
As discussed in the meeting: 

- the deletion is the standard / default Django behavior we can write a cleanup management command to delete them 

The second sounds like a bug in Django itself or django-storages.

**Comment by sdarwin** [comment]
> primary key and a bit of randomness
An idea: if it is predictable randomness, such as a hash of the primary key, the result will always be the same.   If the result is always the same, then it will always over-write itself, and never need clean-up.
