### ISSUE TITLE
Home page: hovering over "Download Latest" makes the text disappear

### ISSUE THREAD

**Issue by anarthal** [cppalliance/temp-site#547]
In Firefox, navigate to https://www.boost.revsys.dev/, and hover the cursor over the "Download Latest" button. The text changs color to the same color as the button, effectively making the text disappear. IMO the effect is a little bit strange.

**Comment by anarthal** [comment]
This is actually happening in light mode with all buttons with Boost Mustard background.

**Comment by williln** [comment]
Looks to be resolved
