### ISSUE TITLE
The support page looks misaligned

### ISSUE THREAD

**Issue by anarthal** [cppalliance/temp-site#548]
Using Firefox, navigate to https://www.boost.revsys.dev/support/. Element placing looks weird.
![support](https://github.com/cppalliance/temp-site/assets/34971811/738b8f65-e37b-49ba-9dcf-55fe66d8ac37)

**Comment by gregnewman** [comment]
@4down Are we not using this? if not, I'd like to remove the route to it.

**Comment by 4down** [comment]
@gregnewman We have the new Contact page linked in the footer so I think whatever this page was, it's no longer necessary.  Agreed on removing the route.

**Comment by gregnewman** [comment]
@4down thanks. I've removed it in PR #871
