### ISSUE TITLE
Sign Up page link "Sign Up with one of your existing third party accounts" that takes nowwhere

### ISSUE THREAD

**Issue by anarthal** [cppalliance/temp-site#550]
In the Sign Up page, "[Sign Up with one of your existing third party accounts](https://www.boost.revsys.dev/accounts/signup/#)" is an `<a>` element, but it isn't underlined and doesn't link anywhere.

**Comment by williln** [comment]
Video: 

https://github.com/cppalliance/temp-site/assets/2286304/9eeb4194-a8e0-4749-b1ee-fb58d75b6dba

Dev Notes: 
- Both links on this page direct to the same page, which is the page the link is on.
- But they direct to different divs -- the social signup div (which is the default, and why the first link doesn't look like a link when you first load the page) or the email signup div. 
- Each link is always present and always clickable, but they are only styled as links when the user is on the opposite option. So I see the email signup link when I also see the social signup content, and I see the social signup link when I see the email signup content. 

Code snippet: https://github.com/cppalliance/temp-site/blob/develop/templates/account/signup.html#L24C9-L40C15

@anarthal I think this is intended behavior but @gregnewman can you confirm?

**Comment by williln** [comment]
Resolved when Greg did away with the show/hide of the two login/signup pages
