### ISSUE TITLE
Mobile menu design

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#552]
Just need to add it, either to the header or inside the mobile menu (which needs to be completed) - but will prioritize getting this in first since we need it to QA on mobile completely.

**Comment by gregnewman** [comment]
We need to really have a design session around what the mobile nav should look like.  The current implementation is what the agency designed.

**Comment by 4down** [comment]
@gregnewman Agreed, but in the interest of letting people QA the site in dark mode on mobile right away, I was just going to quickly add the dark/light mode switch - not necessarily intending it to be anything final.

**Comment by 4down** [comment]
This issue is now for making a new mobile menu that looks "good". In progress. Will include light/dark mode toggle of course.

**Comment by gregnewman** [comment]
This is implemented so I'm closing this issue. If we find any bugs we can create new issues.
