### ISSUE TITLE
Style the "finished resetting password" page 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#596]
Template: `templates/account/password_reset_from_key_done.html` 

<img width="791" alt="Screenshot 2023-08-14 at 10 58 53 AM" src="https://github.com/cppalliance/temp-site/assets/2286304/4b913db3-77b5-4fca-afb4-07185a19db74">

**Comment by gregnewman** [comment]
This is already completed so closing

![CleanShot 2023-10-13 at 11 03 10](https://github.com/cppalliance/temp-site/assets/2026/3f5a3c3f-8609-436f-92cb-c0894a5241a5)
