### ISSUE TITLE
Style the error messages on the "confirm your email" screen 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#599]
When a new user registers with a social account, we collect their email address. If they use an email address that already exists, they get an error. The errors aren't styled yet. 

<img width="1368" alt="Screenshot 2023-08-14 at 12 04 47 PM" src="https://github.com/cppalliance/temp-site/assets/2286304/99f2baec-da8f-4e3e-9e51-5698fb71d06c">

**Comment by gregnewman** [comment]
The error now look like this

![CleanShot 2023-10-13 at 10 41 08](https://github.com/cppalliance/temp-site/assets/2026/fd6848b1-7b36-4a83-823a-0778d6a9e960)
