### ISSUE TITLE
Library Detail Page Issues

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#615]
Docs seem to take them to just the top level docs for the library.  Need to deep link to the specific library docs.

**Comment by williln** [comment]
@4down @frankwiles Do you know if this is still an issue?

**Comment by 4down** [comment]
@williln I'm not seeing it, was this maybe only affecting specific libraries + versions?  I'll look around and see.

**Comment by gregnewman** [comment]
This is no longer an issue. The link takes the user to the proper library index page.
