### ISSUE TITLE
Release Manager Admin Control Panel

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#625]
Every 3-4 months when an official Boost Release goes live, the release manager (Marshall) runs scripts to upload the archive to jfrog, and update the boost.org website. There are multiple steps involved, which could be incrementally added in Django.  Create a Release Manager Admin UI.

1. Generate the .zip files from the development snapshots and upload to jfrog as an official release. Currently functional. Accomplished with bash or python scripts. The script can continue to be used for now.
2. Download the zip archive, unbundle it, and then upload the contents to S3.  I will write a new command line script.  
3. Update the boost website. So far "./manage.py import_versions" and ./manage.py import_library_versions" will update temp-site, if a new boost release exists. That means Marshall should have a way to run those functions and "update the website".	

Each of those could (separately) be added as links or buttons in the Django admin panel on a page for the release manager. 

Continuing, that admin page should also be able to run all the web maintenance scripts: import_versions, update_libraries, import_library_versions, import_library_version_docs_urls, import_commit_counts.

**Comment by sdarwin** [comment]
I have updated the script `publish_release.py`, and Marshall has merged it.     

Now, a new boost archive will extracted and uploaded automatically to S3, and the website can serve those pages as documentation.

In terms of the above tasks 1, 2, 3 :     

1 and 2 are in-place and functional as command-line scripts.  It's not urgent for them to be added to the website UI, they can continue to be run as before.

3 is still an open issue.   The release manager should have simple access to update the boost website, displaying the new boost version information.

**Comment by williln** [comment]
@sdarwin I think we have what we need in place for this ticket to be closed, right?

**Comment by sdarwin** [comment]
I tested "Import New Releases" and that worked. Great! If there are problems later we could open another issue.
