### ISSUE TITLE
Beta releases on website

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#652]
Every release cycle, there is a phase of a few weeks, when a beta release is published.
This is reflected in git tags:
```
boost-1.82.0
boost-1.82.0.beta1
boost-1.83.0
boost-1.83.0.beta1
```
And in the documentation directories hosted on the website:
```
drwxr-xr-x   8 mclow    mclow       4096 Apr 14 03:08 boost_1_82_0
drwxr-xr-x   8 mclow    mclow       4096 Mar 15  2023 boost_1_82_0_beta1
drwxr-xr-x   8 mclow    mclow       4096 Aug 11 16:23 boost_1_83_0
drwxr-xr-x   8 mclow    mclow       4096 Jul 13 13:20 boost_1_83_0_beta1
```
The beta is shown on [boost.org](http://boost.org/) as available to download, and a copy of docs, in addition to the main download.  Thinking about https://github.com/cppalliance/temp-site, will it be able to handle such a situation where it notices a beta is available and hosts the documentation.  

An added advantage of having such functionality, is we could test the release cycle with Marshall since a beta is not quite a full release it would be safer to test with.   If a release cycle is months away, we could still generate a "beta" release.

Questions from Lacey:

> When the new release is fully released (once boost-1.83.0 is released), should the temp-site clean up/remove its beta releases?

Yes. Checking boost.org, https://www.boost.org/doc/ lists previous versions, but not betas.   Attempting to view beta documentation  at https://www.boost.org/doc/libs/1_82_0_beta1/ redirects the visitor back to https://www.boost.org/doc/libs/1_82_0/ , so even though the  files happen to be on the webserver, they are no longer visible.  

> Do they have artifactory downloads?

Yes. The URL path to the beta is slightly difference from releases:

https://boostorg.jfrog.io/artifactory/main/beta/1.83.0.beta1/

The various zip files formats are the same. .tar.gz, .zip.

> Should the beta releases show up in the “releases” drop downs on the Releases and Libraries pages? (Therefore, do we need to import Library-Versions for beta releases as well?)

Possibly. The documentation of the libraries in the beta release should be available on the website.   If the standard mechanism to accomplish that is through imports such as "import library versions".  Otherwise, since the beta will eventually be deleted, fully importing is not critical.   

Maybe it's easier to use all the same import scripts, and display the betas in the list of standard releases, with a _beta1 or _beta2 tag.

> Is there a need for a new web page specifically to talk about beta releases?

> Is there specific language or other features that the “releases” page for beta releases should have? (Maybe they don’t have all 4 downloads, or you want a note about what to expect from a beta release in general, etc.) Or are they just treated like all other releases?

> The crux of most of these questions is basically, “Is the beta release like any other release as far as the website is concerned, or should it be treated differently?”

A new release is shown on the homepage as "Download Latest".   When a beta is available, "Download Latest" remains the same.  "Try the New Beta" would be additional, so two download links instead of one.

At the moment, Release Notes for all releases are directing to the old boost.org.  That must be changed.  However it is implemented  there will be release notes that are hosted by temp-site.   If that is in place, then "a new web page specifically to talk about beta releases" could be the "release notes page" for the beta.

**Comment by williln** [comment]
## Requirements 

- [ ] Identify a release as a beta release 
- [ ] Able to download most recent beta release 
- [ ] Able to delete old beta releases (when there is a new beta release) 
- [ ] Able to see docs for beta release 
- [ ] Able to link to beta release github 
- [ ] Able to download artifactory downloads for beta release 
- [ ] Able to link to release notes 
- [ ] Add the import of the most recent beta release to the "boost setup" command 
- [ ] Add a management command to import the most recent beta release 
- [ ] Add docs 
- [ ] ? Should beta release show up in the drop-down for the libraries? 
- [ ] ? Should beta release show up in the drop-down for the releases?

**Comment by williln** [comment]
@sdarwin @4down Does this need an API endpoint like the version import (see https://github.com/cppalliance/temp-site/pull/664) or is there some other way I should prep this to be executed? Currently there is a celery task, management command, and it's part of the `boost_setup` management command.

**Comment by sdarwin** [comment]
>  ? Should beta release show up in the drop-down for the libraries?  ? Should beta release show up in the drop-down for the releases?

When a beta has been released, and it's the newest version (beta 1.84.0) it should likely show up everywhere, as a release, in the libraries.  After the new release is published (1.84.0) the beta should disappear.

Does the "Import New Releases" button also import a new beta?  (It should, right?) Perhaps all the same apis and scripts that import normal releases also trigger the beta workflow if they notice a newer beta release is available.

**Comment by williln** [comment]
@sdarwin So the beta release should show if it's newer than the newest full version, but not if it's the beta _for_ the full version or is the beta for an older version. Is that right? Examples: 

 Newest version | Newest beta version  | Show in drop-down? | 
| --- | --- | --- | 
| 1.84.0 | 1.85.0.beta1 | Show beta: beta is for newer major version  |
| 1.84.0 | 1.84.1.beta1 | Show beta: beta is for newer minor version |
| 1.84.0 | 1.84.0.beta1 | Do not show beta: beta is for current most recent version |
| 1.84.0 | 1.83.0.beta1 | Do not show beta: beta is for older version |

**Comment by sdarwin** [comment]
Yes, that looks right.   And of course no need to import many previous beta versions at all.  1.82.0 1.81.0.

**Comment by williln** [comment]
@sdarwin I am going to pull that into its own issue
