### ISSUE TITLE
Send password reset email when user signs up with email, and don't have them enter the pw on the registration page 

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#667]
The consensus is that passwords are *old and busted* and passwordless auth is the *new hotness*. 

We're going to need to essentially change all email logins to be password reset flows that don't ask for a new password and instead simply log the user in. 

The flow will be: 

- user enters their email address and submits form
- we send the registered user an email with the same sort of password reset token used in a password reset flow
- after validating the reset token, but instead of showing them a reset form, we simply log the user in

**Comment by williln** [comment]
- [ ] redirect `/admin/` to the main login screen, since it will want a password 
- [ ] Don't remove passwords entirely, but assume they are not coming back

**Comment by frankwiles** [comment]
Also if email/user already exists and they DO NOT have OAuth creds already configured it should allow them to claim the account.  We're just going to entirely trust Google/Github for this.

**Comment by frankwiles** [comment]
That's a good question, I can see it either way.  @vinniefalco can you tie break us on this?

**Comment by williln** [comment]
@frankwiles @vinniefalco This should also cover signup, not just login, right? So I should be able to sign up from scratch with an email, without GH or Google, and without entering a password?

**Comment by williln** [comment]
Updated: requirements per @4down : 

> I think when a person first goes to Join - they choose an oauth option on the left, the flow is as you had described.  If they choose sign up with email on the right, instead of sending them a password-less email login, just trigger the Reset Password for them.  (so they’ll already have entered a desired password twice on the sign-up form, but that will be ignored since they’ll get the Reset Password; whether or not they choose to use that same password will be up to the user)

**Comment by williln** [comment]
## Remaining Items 

- [ ] When an unclaimed user resets their password successfully, mark their account as `claimed`
- [ ] **Social Auth**: When a user registers with social auth (github, google), and they enter an email that matches an unclaimed user, right now, they get an error that the email address is already in use, and they should log in with that email address, then connect their social account. If they are a maintainer, the instructions are basically the same, except they need to request a password reset for that email, then log in and connect their social account. Should i add those instructions to the same message, or should I go ahead and show them a different message? And/or, should I send the password reset email automatically, if it's an unclaimed maintainer account? (@4down this is the discussion I accidentally skipped in the meeting) 
- [ ] Future imports -- we should consider how future releases will also contain libraries.json files that don't map directly to user accounts (people use multiple emails, or are part of multiple orgs depending on the libs they work in etc.). We already save the libraries.json data on the LibraryVersion record, which will be helpful in matching. But a future enhancement might be allowing a user to have multiple Author and Maintainer records, or adding field(s) to the User model to capture what's stored in the libraries.json files of the libs they work with. Something to make matching the libraries.json to the real Users easier.
- [ ] From email should be `info@cppalliance.org`
