### ISSUE TITLE
Library readme code blocks not text wrapping

### ISSUE THREAD

**Issue by mborland** [cppalliance/temp-site#677]
It looks like the imported text from the library README does not wrap in the code blocks. This ends up with a situation like the attached where it falls outside of the text box. This is from the boost.math page.

System:
Safari 17.0 running on MacOS Sonoma (14.0)
<img width="2672" alt="Screenshot 2023-09-29 at 8 51 12 AM" src="https://github.com/cppalliance/temp-site/assets/3745830/93050c2c-4546-44e9-b282-a50b6270c7ef">

**Comment by gregnewman** [comment]
This is fixed - closing.
