### ISSUE TITLE
Make the "you already have an account alert" yellow and not green 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#692]
Follow up to #667

**Comment by williln** [comment]
@sdarwin @4down Feel free to add different text for the "We already have an account for you" message! We can add that later if we need to, as well.

**Comment by sdarwin** [comment]
there it was again.  :-)  This boostwebsite-bot account is the github token used to import versions and releases.

**Comment by williln** [comment]
@sdarwin How about: 

> We recognize your email address as matching that of a Boost Author or Maintainer, and have already created an account for you. We have sent you an email to reset the password for your account. Once your password has been reset, your account is claimed.

**Comment by williln** [comment]
@gregnewman Can you remind me which "yellow" to use? I think you mentioned a specific place in the code to look for a message we have styled this way already (or am I imagining that?)

**Comment by gregnewman** [comment]
@williln there is an alert in libraries if there is a mismatch of version. That is the same yellow.

**Comment by sdarwin** [comment]
> @sdarwin How about: We recognize your email address as matching that of a Boost Author or Maintainer, 

Yes that looks fine. 

I am researching mailman now to see if something should also be done about mailing list members or they will follow a new user signup.  Maybe the text will change to "matching that of a Boost Author, Maintainer, or community member."    But that can change later in a different commit.

**Comment by gregnewman** [comment]
@williln did you or are you handling the yellow bits here?

```
<div role="alert" class="py-2 px-3 mb-3 text-center rounded-sm bg-yellow-200/70">
```

This is what I'm using in `templates/libraries/includes/version_alert.html`

**Comment by williln** [comment]
@gregnewman Yes that's me! Thanks!
