### ISSUE TITLE
Library page doesn't look great

### ISSUE THREAD

**Issue by anarthal** [cppalliance/temp-site#698]
https://www.preview.boost.org/libraries/mysql/boost-1-83-0/

* The "Maintainers" section appears without any name or profile picture, so the lib looks like it was unmaintained (when it's not)
* It's trying to (unsucessfully) render the `README.md`, but bullet points are not showing.
* The CMake code snippet doesn't have accessible colors (I have no visual problems and I can't almost see it). This is not that bad under dark theme, but is more severe under the light theme.

**Comment by gregnewman** [comment]
Can this be closed @4down ?

**Comment by anarthal** [comment]
Has this been deployed? https://www.preview.boost.org/libraries/mysql/boost-1-83-0/ looks similar

**Comment by gregnewman** [comment]
I don’t think it’s in staging yet
