### ISSUE TITLE
Error handling - When data is missing (ie, libraries), give helpful message

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#700]
When someone builds the site locally and hasn't done any data imports or generated dummy data, we should give a message alerting what the problem is instead of having things explode when navigating to the libraries page (for instance; any page where this might happen should have a similar helpful message given).

**Comment by williln** [comment]
@4down Would you want this to be a 404, or a redirect to the homepage with a message or something?

**Comment by williln** [comment]
@4down I opened a PR for this one
