### ISSUE TITLE
Static/site pages are not currently working

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#714]
1.  Static/site pages are not currently working

For example, https://github.com/cppalliance/site-docs/blob/develop/site-pages/help.adoc exists on https://www.boost.revsys.dev/help/ - but this gives a 404 on preview.boost.org and stage.boost.cppalliance.org

2. Configured for stage vs prod 

Assuming for prod, it would need to pull from site-docs/master.  If there will be a stage_static_config and a prod_static_config, can we exclude that from the paths and assume it?

3. Fallback URL  

It looks like we have a fallback URL path for any adocs under site-docs that aren't explicitly mapped to their own URL but I can't get those to work on revsys staging.  ie, https://github.com/cppalliance/site-docs/blob/develop/site-pages/users/people.adoc looks like it would map to https://www.boost.revsys.dev/doc/users/people/ but that isn't working.  This is presumably the same issue as #1. 

Can we change that fallback URL path to something other than /doc/ - https://github.com/cppalliance/temp-site/blob/704e7d73821b3c6c7ff3856fd0af0843bbaa0939/stage_static_config.json#L35 - since these pages aren't meant to be grouped with the other docs from that repo on the site.  /page/ or /p/ ?  Does anyone have a preference or want to leave it as-is?

**Comment by williln** [comment]
Can confirm @sdarwin that #1 is fixed.

**Comment by williln** [comment]
Closed by https://github.com/cppalliance/site-docs/pull/144

**Comment by williln** [comment]
@sdarwin @4down I broke the other two topics out into their own issues to make it easier to keep track of, and closed this one since one of the three items was complete. I'll resume discussion in the new issues!
