### ISSUE TITLE
Separate staging and production static config files

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#725]
Broken off from #714 

From @4down: 

> Assuming for prod, it would need to pull from site-docs/master. If there will be a stage_static_config and a prod_static_config, can we exclude that from the paths and assume it?

From @sdarwin: 

> Just noticed that! "stage_static_config" is hard-coded to point to a `/develop/` folder. Based on such a design there will need to be both a "stage_static_config" and a "prod_static_config" so that production can point to the `/master/` folder.

> Unless it can be made to dynamically pick up a variable such as `deploymentEnvironment: &env production` from the kube files and switch between /develop/ and /master/ .

**Comment by frankwiles** [comment]
@williln let's make sure we can set the path file as an ENV var so it can be easily set which is in use by each deployment.
