### ISSUE TITLE
Commit bar chart does not match dark theme

### ISSUE THREAD

**Issue by mborland** [cppalliance/temp-site#729]
Navigating to any of the library pages with system dark mode enabled the page will be dark mode as expected, but the commit bar chart shows white. Additionally, hovering over a bar brings up a box with no text next to the legend color (or its white as well). Both issues can be seen in the attached screenshot.

System: Safari 17.0 running on macOS Sonoma 14.0

<img width="1233" alt="Screenshot 2023-10-20 at 8 41 38 AM" src="https://github.com/cppalliance/temp-site/assets/3745830/80f9c342-8ec4-46ac-8640-d66d71638bc3">

**Comment by gregnewman** [comment]
debugging this, it seems to only happen on initial load. when changing themes it correctly changes the chart.
