### ISSUE TITLE
Get Hyperkitty Installed

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#736]
Install Hyperkitty with a copy of the archive unstyled.

**Comment by frankwiles** [comment]
@sdarwin how do you want to slice this up? Me or @williln can get it installed and you load the archive?

**Comment by sdarwin** [comment]
> Me or @williln can get it installed

Install the mailman-web components in Django. Yes.

Mailman-core servers have been installed:  

mailman.boost.cppalliance.org
mailman-stage.boost.cppalliance.org
mailman-cppal-dev.boost.cppalliance.org
mailman-revsys.boost.cppalliance.org

The core servers ought to be re-installed using new DNS.  For now, they may be enough to test. 

If we merge pull request 611 (how about on Monday, merge that) the information to reach those servers will be available to the web frontend.

MAILMAN_REST_API_URL = env("MAILMAN_REST_API_URL", default="http://localhost:8001")
MAILMAN_REST_API_USER = env("MAILMAN_REST_API_USER", default="restadmin")
MAILMAN_REST_API_PASS = env("MAILMAN_REST_API_PASS", default="restpass")
MAILMAN_ARCHIVER_KEY = env("MAILMAN_ARCHIVER_KEY", default="password")
MAILMAN_ELASTIC_INDEX = env("MAILMAN_ELASTIC_INDEX", default="haystack")

Those environment variables are provided by kube secrets.   Which have been uploaded in the cluster.

**Comment by frankwiles** [comment]
Skipping this plan in favor of a separate Django project running Mailman/Hyperkitty and using Boost.org's auth via OAuth2
