### ISSUE TITLE
Lozenges - Get the plus out

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#742]
Only the number should appear in the lozenges.  Appears in all library list item templates as well as the detail template, but searching for "cpp_standard_minimum" is a great idea.

![image](https://github.com/cppalliance/temp-site/assets/49487079/006ef8e5-25e1-4463-ac2e-13916a150375)

**Comment by vinniefalco** [comment]
Visine gets the red out, so what gets the plus out?

**Comment by 4down** [comment]
Minusine

**Comment by 4down** [comment]
Missed a + on the detail page.
