### ISSUE TITLE
Pulling in calendar data from the community-maintained events calendar

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#760]
The calendar whose data we need currently lives at https://www.boost.org/community/index.html

We'll want to pull the data and use it:

1. On the homepage in succinct line item form
 a. Using the same layout/functionality as the hardcoded "Schedule of Events" section currently on the new homepage or 
 b. If there is a suggestion or idea for something that might work better, we should discuss.

2. On a new page where it can be displayed more fully as it currently works at the old site (but looking nicer than how it looks on the old site - looked like the example shown during the 10/27 meeting would work)

3. We should check with the current primary maintainer of this calendar and determine if this calendar is only going to be a release schedule, or if there is a possibility of including community-contributed events (or, any non-release events no matter who is contributing that information).
 a. If it will be strictly a release schedule, it makes sense that the page will live in the Releases section
 b. If it will include other events, I think it makes sense for it to live in the Community section (and a link to it would be provided on the Releases page)

I'll look into the third item there to make a decision on where that page will live, in case that has any bearing on where in the site architecture any of the code would best live.  

@frankwiles, let me know if there's any info you need.  If access to the calendar on Google is needed, for instance- if you don't already have it.  Thanks!

**Comment by frankwiles** [comment]
@sdarwin Lacey needs creds for this one.

**Comment by sdarwin** [comment]
See pull request 874

**Comment by williln** [comment]
Note to self: events on the homepage need caching!

**Comment by williln** [comment]
@4down @sdarwin @frankwiles This is done. The only remaining items are: 

> I'll look into the third item there to make a decision on where that page will live, in case that has any bearing on where in the site architecture any of the code would best live.

Currently, the events are on the homepage and on their own `calendar` page, but the calendar page isn't linked from anywhere. https://www.preview.boost.org/calendar/

Just let me know what else should change and then we can close the ticket!

**Comment by 4down** [comment]
@williln The homepage update looks and works great!

I'll take care of finding the calendar page its new home.  If no one else has anything to add on this, we can close it out.  

Thanks!
