### ISSUE TITLE
Homepage - Download button needs to show its strength and overpower the Slack button

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#761]
Currently the Slack button catches the eye more due to its colorfulness, especially in dark mode with the white background.

The white background needs to stay per Slack branding terms of use, so will need to make some changes for the download button to stand out first, or at least, to clearly be the more important button of the two.  

Possibilities: 

- Bigger/better/badder icon for the download button
- Size adjustments, increasing size of the download button and/or decreasing the size of the Slack button
- Font adjustments, larger and/or smaller, etc.
- Accompanying information with the download button, placed below it, to help call out to it more.  This would be done in combination of other changes.

But will experiment and a solution will precipitate.  A solid solution.

![image](https://github.com/cppalliance/temp-site/assets/49487079/8c32a146-5591-47de-b49f-47868b084128)
![image](https://github.com/cppalliance/temp-site/assets/49487079/7a392ab0-bec7-4fc0-a320-216828fc0b91)

**Comment by 4down** [comment]
@gregnewman Per your feedback on the call, the spacing between the Slack button + text below will be getting tweaked as a part of this!  Thanks!

**Comment by 4down** [comment]
Also with this update, need to fix the issue where hovering outside of the actual button(s) triggers the hover states in the button(s).  (for sure is affecting the Download button)

**Comment by vinniefalco** [comment]
its a nice button but we have decided not to promote the Slack workspace for now.
