### ISSUE TITLE
Error on submitting a news item

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#765]
Per @grisumbras,

- Submitted news item to preview.boost.org.   Got 500 Server Error.

- I just clicked "Submit"

were you logged into the website before the submit?

- Logged in, as far as I can tell. But the Error 500 page looked like I wasn't (it had a "log in" link). I mean, I was logged in, and I am logged in now. But, after I clicked "Submit" it was considering me not logged in, because the error page showed me the "Join" link

**Comment by frankwiles** [comment]
@sdarwin Can you dig up some logs on this? I haven't tried it recently but it worked fine locally and on the REVSYS site recently.

**Comment by sdarwin** [comment]
@grisumbras is this easily replicated?  If so, please post

1. The URL you visit. Is it https://www.preview.boost.org/news/add/link/ ?
2. Any combination of Title and URL will cause an error to appear?

I have posted a link using that URL without an error occurring.

**Comment by sdarwin** [comment]
duplicate of 773. Closing.
