### ISSUE TITLE
News items display

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#769]
News listings display needs updating.  

TBD all changes, but these seem like a reasonable starting point:

- Title of item links to news detail page
  - This is always necessary even for Link types since this is the only page a user can edit/delete from
- URL displayed underneath, directly linking to the URL
- If content exists, have short preview.  No need for any "Read more" link since the title of the item links to it.
- Include the author's name followed by published date after
- If an image was added, the image needs to have some styling applied.  Should not be floating extreme right of the item info, if there was no description, the image can appear where the description would have.

**Comment by 4down** [comment]
@gregnewman I forgot I had assigned this to myself.  

I like what you showed me already, but I do think we should have the author's name and the published date displayed.  Along with having the image appear more nicely (or, I'm not opposed to not actually showing the image here either and only having it on the detail page).

**Comment by gregnewman** [comment]
@4down this has been merged in PR #830 so if you confirm the work you can close it.
