### ISSUE TITLE
User avatar - .heic file types

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#771]
![image](https://github.com/cppalliance/temp-site/assets/49487079/24218a92-5eff-4426-ad93-b25e924a4c56)

End up appearing as broken images.  Either need to find solution to display them properly, or use the default user avatar.

**Comment by gregnewman** [comment]
Try it with a jpeg. I don't think the backend supports heic but should not allow an upload of that file type if not.

**Comment by 4down** [comment]
@williln - We should be preventing users from uploading files other than JPG, PNG, and GIF.  For both profile photo and news image.

For profile photo, we should limit the file to 1MB.  I think this is also what we should limit the news image to.  One of the news posts now has a 4032x3024 jpg and it is ~770kB.  

GitHub doesn't allow >1MB either for profile pictures - 
```
Note: Your profile picture should be a PNG, JPG, or GIF file, and it must be less 
than 1 MB in size and smaller than 3000 by 3000 pixels. For the best quality 
rendering, we recommend keeping the image at about 500 by 500 pixels.
```
Will need to return appropriate error response to the user.  Also, just to check, but if the file upload is editing/changing an existing image, want to be sure that the existing image is only deleted after the uploaded file is verified as OK!

**Comment by 4down** [comment]
Also disallow GIFs.  Only JPG and PNG.  JPEG would also be acceptable.  Thanks!

**Comment by 4down** [comment]
@williln Do you know of any Python/Django library/plugin that can easily determine if an image has any transparency?

**Comment by williln** [comment]
@4down 

> Do you know of any Python/Django library/plugin that can easily determine if an image has any transparency? 

Does this help? https://stackoverflow.com/questions/43864101/python-pil-check-if-image-is-transparent#:~:text=getcolors()%20).,smallest%20value%20falls%20below%20255. I haven't done a lot with images in Python beyond basic uploading and some resizing, but PIL is the library I've used for those things and it looks like it has the "transparency" detection you're talking about.

**Comment by gregnewman** [comment]
I don't think transparency is an issue if we border the container. No need for overhead.

**Comment by 4down** [comment]
@gregnewman Agreed, adding a border is my preferred way to handle it and I think it's settled on now.  Sorry @williln no need to worry about transparency detection, but we do want to still restrict by file type and size.  Thanks!
