### ISSUE TITLE
Avatar image aspect ratio issue(s)

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#774]
We should be using object-fit: cover on the avatar where appropriate so that avatars that are not squares still appear nicely.

![image](https://github.com/cppalliance/temp-site/assets/49487079/a595bb83-2db1-462f-9834-32d2d62e5288)

Need to test on other browsers, check to see if the avatar image on Profile Update has incorrect height/width attributes or maybe none at all - that could cause it to move as the page is loading.  Possible that we can use the same object-fit as above and make it a square everywhere?

**Comment by gregnewman** [comment]
@4down I know what's causing this. I'm assigning to me, it's a quick fix.
