### ISSUE TITLE
Download Button is not Symmetrical

### ISSUE THREAD

**Issue by mborland** [cppalliance/temp-site#780]
The text in the "Download the Latest Release" button at the top of the homepage is not centered in the button.

<img width="1398" alt="Screenshot 2023-11-01 at 8 16 26 AM" src="https://github.com/cppalliance/temp-site/assets/3745830/2c724c3b-84e6-4303-85b1-161199d45b3c">

**Comment by 4down** [comment]
Try doing a hard refresh.

**Comment by mborland** [comment]
Cleared cache and seems to be fine.
