### ISSUE TITLE
News - Restrict user's ability to add a post if they do not have a profile photo

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#793]
Users without photos, don't allow posting.  

We'll need to give feedback to the user letting them know the reason.  Let's discuss the best way to do that, but for now we should make sure the actual news post page can't be directly accessed by someone without a photo - right now it sends a user to the login page if you try to access /news/add/ when not logged in, so we probably want to send them to the profile update page in this new case.

**Comment by vinniefalco** [comment]
When a user without a profile picture presses the "Submit News" button they can be taken to an error page which explains the circumstance and then offers them a link to their profile where they can add the avatar.

**Comment by 4down** [comment]
My thought is that having an actual button for Create Post would work best, and for users not logged in or without a photo, the button will be in a disabled state with accompanying text letting them know the reason.

Then we could change the opening paragraph to:

> Stay up to date with Boost and the C++ ecosystem with the latest news, videos, resources, polls, and user-created 
> content. Registered users can submit posts to the feed, but please note that all posts are reviewed before being 
> published on the site

The text with the button can say either:

"Please [link]Log In[/link] to create a new post." or "Please [link]Upload a Profile Photo[/link] before creating a new post."

**Comment by gregnewman** [comment]
It looks like this is a discussion on how to handle this. Do we have this confirmed and if so can you clarify?

**Comment by 4down** [comment]
@gregnewman For now let's just go with the simple solution, so basically what Vinnie had said - but let's cut out the intermediary page in the proces.  

If the user attempts to access the create post page and they don't have a profile photo, forward them to the profile edit page, and have a notification along the top that explains that they need to upload a profile photo before they can submit a post.
