### ISSUE TITLE
News detail page - Include author name and photo, links to other posts by author

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#794]
Definitely need this on the page, to credit the person who submitted it.  But it will also help to make the page look nicer.

Another element that will make the page not feel like a wasteland would be to have links to, say, up to the latest 5 posts by the same author.  If there are no other posts by the author, the latest 5 by any author.

**Comment by gregnewman** [comment]
@4down what context do you want in the list of 5 other posts? (title, date, etc)

**Comment by 4down** [comment]
@gregnewman I think just reusing the list display that's used on the listing page would be fine.  Is that what you mean?

**Comment by gregnewman** [comment]
Reuse the list display for the five most recent exactly as it is in the listing with icon, avatar and block?

**Comment by 4down** [comment]
@gregnewman Let's hold off on adding this to the page for now.  I know we want to get away from the Newer/Older buttons there, but the page looks a lot nicer with the changes you've made - so we'll table this unless any specific feedback comes up.  

You've got the author/image showing on the page now so going to mark this as completed.
