### ISSUE TITLE
Set up a CDN (Cloudflare) for anonymous visitors, static content pages

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#799]

**Comment by sdarwin** [comment]
Cloudflare would require migrating the entire boost.org DNS domain to Cloudflare.  Not merely the website, but everything, by pointing the NS records at the service.  

Even if that move is ultimately approved it probably wouldn't be until after many more meetings.    Therefore, what are the alternatives?  Fastly, Cloudfront.. since we are already on GCP, their offering is "Cloud CDN". https://cloud.google.com/cdn/?hl=en

"Google Cloud CDN and Cloudflare are both great solutions. Google Cloud CDN is the fastest and will be a delight to use if you already utilize Google Cloud Services."
"Highly recommended to implement if you are already using other Google Cloud Services"  
"It is one of the most secure and fastest CDN available globally."
"It drastically reduces the latency, so the loading time of the content is reduced as well."

I think the next step should be testing stage.boost.cppalliance.org with "Cloud CDN".  This week I was running load testing https://github.com/locustio/locust , and can direct web traffic at the site (before/after a CDN is in place.)

**Comment by frankwiles** [comment]
Normal "CDN" services aren't what we need, we need an edge side cache that is smart.  So Fastly is an option, but likely to be quite a bit more expensive than CloudFlare unless you can work a deal with them due to Boost being Open Source (for example they host all of Python's PyPI for free for some advertising). 

 The other option is to host Varnish ourselves in front of the Django app. 

In either case, adding some Django level caching (and cached sessions for logged in users) would go a long way to improve performance at scale.

**Comment by sdarwin** [comment]
- Fastly:   is the most customizable and smart edge cache. The pricing of $.12 per GB would be $120/month at 1TB of traffic for the website. Not extremely expensive. Boost archive downloads continue to be hosted on JFrog. The choice of CDN for the downloads is not required to be the same as the website.

- "Cloud CDN":  to explore the idea, could the service do these tasks?

1. cache all anonymous content 
2. cache html text in addition to images and js
3. not cache authenticated pages.    

- Currently Django is setting the header "Vary: Cookie, origin" on all html pages.  Those would not be cached. To fix this, unauthenticated users would need to have "cookie" removed from the Vary header.

- Cloud CDN won't cache html text unless Cache-Control is included in the headers. So, Cache-Control would need to be added for unauthenticated users.

- As long as "Vary: Cookie, origin" continues on authenticated pages, they would not be cached, which is correct.

Perhaps some forward progress could be made using Cloud CDN to implement edge-caching and remove traffic from the origin. 

At the same time, Fastly is much more customizable and can implement any caching rules. So, let's try that. We could still switch CDNs in the future if necessary.   And if the Boost Foundation agrees to migrate all DNS to cloudflare.

**Comment by sdarwin** [comment]
The main performance concern is with the boost documentation.  Pages like https://www.preview.boost.org/doc/libs/boost_1_83_0/doc/html/accumulators.html

In the long term, configuring Edge-Side Includes (ESI) on the CDN would enable caching even when authenticated.  

In the short term, if the documentation page headers could display an anonymous profile photo in the upper right corner instead of the actual profile photo, then  in exchange for this very small sacrifice all documentation pages would be cached and optimized by the CDN.   (Set up the caching policy to remove Vary: cookie on doc/ pages)

Add Edge-Side Includes (ESI) in the future.

**Comment by sdarwin** [comment]
This is basically completed. The Fastly CDN has been configured to cache pages.  It will still need to be adjusted if/when we have access to the main website domain.  Also fine-tuning later.
