### ISSUE TITLE
News / Library Spotlight Box Shape

### ISSUE THREAD

**Issue by mborland** [cppalliance/temp-site#800]
It looks like the library spotlight box and recent news boxes were at one point separate, but they are now merged together leaving a notch at the top and bottom of the unified box.

<img width="1294" alt="Screenshot 2023-11-03 at 8 39 41 AM" src="https://github.com/cppalliance/temp-site/assets/3745830/48e1a7d5-3dce-4d10-86ec-8b633c6bfd52">

**Comment by 4down** [comment]
This will be resolved when #798 is, but leaving open until then so I am sure of it.
