### ISSUE TITLE
News: Make sure first & last names + profile photo exist

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#805]
We need to capture user's first and last names on sign-up.

**Comment by 4down** [comment]
@frankwiles - Did we get all of the info we needed for the new login flow?  This issue is part of revamping the entire login process.

**Comment by frankwiles** [comment]
No, there was a flurry of contradictory changes in that meeting.  If someone can work up a detailed flow of what is wanted I can get @williln working on it.

**Comment by 4down** [comment]
I'll write something up and make sure it's approved.

**Comment by 4down** [comment]
Not approved yet.  To discuss.

- Join page will be combined login and sign-up forms.  Layout stays the same as sign-up page.
    - GitHub/Google buttons on left
    - Email/password on right
    - Text changed to note that this is for both signing up and logging in
- User does not have an existing account
    - Chooses GitHub or Google
        - Creates account for user using info from connector
        - Should populate email, first and last names, and profile photo
        - Should user need to enter a password here also?
        - If connector cannot populate name or photo, should direct user to registration form
          - Registration form - Pre-fill any fields the connector could populate, all fields required
    - Enters an email address and password
        - Since account does not exist, they are taken to registration form
        - Should there be an email sent to them first for security reasons? (Make sure the person actually has the email they’re using)
        - Registration form - Pre-fill email and password, additional required fields for name and profile photo
- User has an existing account
    - Chooses GitHub or Google
        - If they have never added the connection, it should create connection with existing email-password account automatically
        - Logs them in
    - Enters email/password
        - If a password is required to be created for all users, nothing needs to be done here if they had an existing account via GitHub/Google only.
        - Logs them in

- Requirements
  - **Users must always have email, first and last names, and profile photo.**  
  - Password?  If we always require a password to be created, then there is no issue in having a user who signed up first using a connector later wanting to log in using their email.  It would just work.

**Comment by williln** [comment]
@4down Was this approved? If so, I can work on it.

**Comment by frankwiles** [comment]
@williln will get approval clarification today, but changed it from assigned to me to assigned to you for when the time comes

**Comment by 4down** [comment]
The previous notes RE: new login process are on hold at least for now, any future discussion about it should go into a new issue.

The original issue here was that we wanted to make first and last names required at sign-up, strictly for use in the news section when the user is posting.  Since the number of users who actually submit posts should be a relatively small % of the total users, for now we should just be sure that when someone goes to create a news item, that it will give them a message and forward them to the profile update screen if needed.

@gregnewman I think you may have already taken care of this. (users missing profile photo and first/last name who try to submit a post are sent to the profile edit screen if trying to post)  If so, we can close this.  Thanks!

**Comment by williln** [comment]
@4down @gregnewman I tested this in preview and I was redirected to the profile page when I didn't have a photo, but not when I didn't have a first/last name. So it looks like the name requirement hasn't been implemented yet.
