### ISSUE TITLE
Bug -- categories are not loaded for many libraries 

### ISSUE THREAD

**Issue by williln** [cppalliance/temp-site#808]
See if there is something wrong in the load script.

**Comment by williln** [comment]
@4down @sdarwin @frankwiles After we discovered that many libraries in the `preview` site don't have categories, I took a look, and it looks like the preview site doesn't have all of the categories. I suspect the initial command to load the database was interrupted and didn't finish. 

To make it easier to refresh this data, I added a button to the admin (like the one we have to import new releases). Once this PR is merged, follow the instructions in the PR (which are basically to click the button), and the problem should be fixed. 
https://github.com/cppalliance/temp-site/pull/818

**Comment by sdarwin** [comment]
> basically to click the button

Done. Categories have updated.
