### ISSUE TITLE
Log In with GitHub error

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#826]
This could be a temporary issue, but this is what I am getting on prod (preview.boost.org) when trying to connect with GitHub right now.

The URL that gives this response is .. oh.  Now the error makes sense.  We should probably try to prevent this from happening. :grinning:

https://www.preview.boost.org/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/accounts/github/login/callback

![image](https://github.com/cppalliance/temp-site/assets/49487079/5ed67c9d-93c7-4d59-86f5-5f7adfec15f5)

**Comment by sdarwin** [comment]
@4down , I have seen that error happen when the web URL was different than expected. (stage instead of preview), after the production database was imported to staging.  

However in this case, could it be due to having multiple social auth accounts?  You are in the database with both "GitHub" and "Google".   Try using the other one.

**Comment by 4down** [comment]
This issue is resolved now.  Not an issue that we would ever see in the wild, so there is no reason to try to catch this error.  (the problem was created from syncing databases between servers)

**Comment by 4down** [comment]
see #815

**Comment by sdarwin** [comment]
- this happened on stage, and was fixed by manually resetting the socal auth id and key after imported the production db.
