### ISSUE TITLE
Profile image on docs pages

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#872]
@gregnewman the htmx seems to be working very well !!  

A small issue. Without a profile photo the image is now slightly off-center:  

![Screenshot from 2023-12-15 10-45-44](https://github.com/cppalliance/temp-site/assets/1257803/93ba1c71-dd1b-4cde-8623-0687467b9e6f)

**Comment by gregnewman** [comment]
There are multiple issues there that I’m working on. Thanks @sdarwin

**Comment by sdarwin** [comment]
The latest release 1.84 doesn't show headers on the docs pages

https://www.preview.boost.org/doc/libs/boost_1_84_0/doc/html/accumulators.html

**Comment by gregnewman** [comment]
@sdarwin what I'm finding is it looks like for version 1.84.0 something has changed in the structure of the docs that are generated.  Do you know if anything changes in the templates/processes? 1.83.0 works fine.

**Comment by sdarwin** [comment]
It is possible that something changed in the structure of the docs, although not sure what.  

boost.org also injects headers. That is still working as before: https://original.boost.org/doc/libs/1_84_0/doc/html/accumulators.html

**Comment by gregnewman** [comment]
@sdarwin can you get me credentials to the s3 bucket so I can diff the templates?

**Comment by gregnewman** [comment]
If the tarballs on jfrog are accurate then there is no difference so I'm digging deeper.
