### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by sdarwin** [cppalliance/temp-site#878]
1. Release downloads currently have an extra slash `//boost_1_84_0.tar.gz`  

https://boostorg.jfrog.io/artifactory/main/release/1.84.0/source//boost_1_84_0.tar.gz

2. Future issue: Is there a way to update the download URLs for all past and future releases?  The jfrog links will change soon. They are asking us to implement a CDN.  In config/settings.py it says `"ARTIFACTORY_URL", default="https://boostorg.jfrog.io/artifactory/api/storage/main/"` .   `/api/storage/main/` is not part of the download path so that's something else.

**Comment by williln** [comment]
@sdarwin #880 is merged, which fixes the extra slash. So now, you can run `./manage.py import_artifactory_release_data` in stage and preview, and the Artifactory links will update to remove the extra slash. There is not currently a button in the admin that will do that (the admin button only pulls in new release information), but if a button that would refresh the existing release and library data would be helpful, we can make a new ticket for that. 

For the future issue, yes, we can update the links. Let me know when their links change and I can take care of that. The `ARTIFACTORY_URL` is our API endpoint for them, and we use the data they give to use to store the download links, so I think it will be simple to do. 

Let me know if this addresses your issue, and if so, I will close the ticket and we can open a new one for changing the download links when JFrog wants us to.

**Comment by sdarwin** [comment]
@williln, awesome, the extra slash is fixed!

At the beginning of the script, on both stage and production, there was one error.    Not sure if it means anything.  Generally everything worked.

```
root@boost-7ff8ff7858-bc49z:/code# ./manage.py import_artifactory_release_data 
{"message": "Signal handler <function setup_periodic_tasks at 0x7e3e3c28a700> raised: AttributeError(\"'str' object has no attribute 'name'\")", "exc_info": "Traceback (most recent call last):\n  File \"/venv/lib/python3.11/site-packages/celery/utils/dispatch/signal.py\", line 276, in send\n    response = receiver(signal=self, sender=sender, **named)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/code/config/celery.py\", line 31, in setup_periodic_tasks\n    sender.add_periodic_task(\n  File \"/venv/lib/python3.11/site-packages/celery/app/base.py\", line 1019, in add_periodic_task\n    key, entry = self._sig_to_periodic_task_entry(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/venv/lib/python3.11/site-packages/celery/app/base.py\", line 1032, in _sig_to_periodic_task_entry\n    else self.signature(sig.name, args, kwargs))\n                        ^^^^^^^^\nAttributeError: 'str' object has no attribute 'name'"}
Stored download data for boost-1.81.0
Stored download data for boost-1.81.0
Stored download data for boost-1.81.0
Stored download data for boost-1.81.0
Stored download data for boost-1.79.0
Stored download data for boost-1.79.0
Stored download data for boost-1.79.0
```

>  when JFrog wants us to

Might switch to Github Releases downloads instead.   Not known yet.  Can close this issue.

**Comment by williln** [comment]
@sdarwin Looks like something related to the task scheduler -- I will take a look but I think it's unrelated to this. Thanks for letting me know!
