### ISSUE TITLE
Use Tailwindcss search box for Libraries 

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#88]
- [x] Make search box more prominent 
- [x] Use JS client side
- [ ] Ensure library authors review their descriptions to make for good searches

**Comment by gregnewman** [comment]
Styles search results to break up title from description...

![CleanShot 2023-02-24 at 10 04 12](https://user-images.githubusercontent.com/2026/221212075-e35fce26-db9b-4549-a893-fce97de9caeb.png)
