### ISSUE TITLE
Add Funding Acknowledgment for C++ Alliance, Inc.

### ISSUE THREAD

**Issue by louistatta** [cppalliance/temp-site#883]
To provide transparency and due recognition, please add a footer statement on each page (**excluding the User Guide**) acknowledging the financial support from C++ Alliance, Inc. and adhere to good practice in acknowledging funding sources.

### Implementation
The following statement will be added to the footer of each applicable page:

"Website funded by C++ Alliance, Inc."

### Additional Notes
The link to the C++ Alliance, Inc. website will be included in this acknowledgment.

**Comment by vinniefalco** [comment]
"funded" is _gauche_. Consider "Website supported by grants from The C++ Alliance."

**Comment by 4down** [comment]
@louistatta Is it only the User Guide which is excluded?  Meaning, Contributor Guide & Formal Reviews should have it, or exclude all pages which fall into that overall documentation section?

What about the library docs?  ie, https://www.preview.boost.org/doc/libs/boost_1_83_0/

I'm handling it on the main front-end site now.

**Comment by louistatta** [comment]
Leave it out of the document section.
