### ISSUE TITLE
Add Slack Cpplang Channel to Community Page

### ISSUE THREAD

**Issue by louistatta** [cppalliance/temp-site#884]

**Comment by louistatta** [comment]
## Description for Cpplang Slack Workspace

New description to our community page:

"Cpplang Slack Workspace: A vibrant hub for real-time discussions with Boost authors, maintainers, and contributors. Dive into one of the largest searchable databases for Boost/C++ insights and history. Join now."

**Comment by 4down** [comment]
@louistatta @vinniefalco 
Do we want to add this back to the Learn page also while I'm at it?

![image](https://github.com/cppalliance/temp-site/assets/49487079/908c560a-ce22-4944-83cb-f6d14bfbbcb8)

**Comment by louistatta** [comment]
not on the learn page.
