### ISSUE TITLE
Sample static content with images

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#886]
Hey @williln, @4down asked in the meeting if you could put together an example static page that included images just as a reference for him as he builds out the various static pages for launch.

**Comment by williln** [comment]
@4down Can you say more about what you're looking for? Many of the docs pages include images.

**Comment by 4down** [comment]
@williln I mean a page that is not part of the docs, a standalone static content page - like https://www.preview.boost.org/help/ but with images.  Something that anyone could use as a starting point.
