### ISSUE TITLE
Issue with News Posts Always Showing '...'

### ISSUE THREAD

**Issue by louistatta** [cppalliance/temp-site#893]
I've noticed something a bit odd in the news section. Every post, no matter how short, ends with "..." like there's more to read. But when you click on it, there's nothing extra – what you see is what you get.

What's Happening:
In the news section, all posts, even the short ones, end with "...".
When you click on these posts, expecting more, there's actually no more text.

What Should Happen:
I think the "..." should only show up if the post is actually longer than what's being displayed. If the whole post fits in the preview, then there shouldn't be any "..." at the end.

How to See It:
Just go to the news section.
Look at any short post and you'll see the "..." at the end.
Click on it and you'll see there's no extra text.

This is a bit confusing and it's a tad annoying thinking there's more to read when there isn't.

**Comment by 4down** [comment]
@louistatta Got it, I'll make sure this isn't happening when I merge in the truncate changes.  Thanks!
