### ISSUE TITLE
Should be able to mark old library versions as not having docs

### ISSUE THREAD

**Issue by frankwiles** [cppalliance/temp-site#899]
Simple boolean flag on the model so we can NOT generate the URL we generate *optimistically* assuming the docs exist in S3. 

We don't plan to use this feature often, but might come in handy. Should just NOT show the docs URL on the detail page for that one version.

**Comment by sdarwin** [comment]
the current fallback of showing the entire release as the documentation such as https://www.preview.boost.org/doc/libs/boost_1_35_0/index.html isn't bad, and arguably it's better than no docs at all.  Rather, step by step over time, add customization to improve the locations of the URLs, try to point at the target pages.
