### ISSUE TITLE
Docs header issues w/ logo position on at least base doc page & missing default user icon in dark mode

### ISSUE THREAD

**Issue by 4down** [cppalliance/temp-site#907]
The header in the docs pages is affected by the user's choice of dark or light mode at the main site.  That might be fine, but, in dark mode the user profile photo for people with the default user icon is empty:

![image](https://github.com/cppalliance/temp-site/assets/49487079/4bb456f7-4c15-4441-948a-da66a2ac2640)

vs

![image](https://github.com/cppalliance/temp-site/assets/49487079/5b132fd3-4ae5-49f9-80aa-5be6a18232b2)
(when in light mode)

@gregnewman Not sure if this is something that's in progress, but wanted to capture it to be safe.  Let me know if it's something I can take a look at.  Thanks!

**Comment by 4down** [comment]
https://www.preview.boost.org/doc/libs/boost_1_57_0/index.html has logo shifted up (possibly affects other versions but not sure)

**Comment by 4down** [comment]
Updated the title of this issue to better capture that this refers to 2 issues, @gregnewman if you prefer that we split the two in their own issues, let me know and I'll do that.  Thanks!

**Comment by gregnewman** [comment]
@4down I merged two commits that fix these issues
